clear
python3 /home/ubuntu/Desktop/live/A.py &
python3 /home/ubuntu/Desktop/live/AA.py &
python3 /home/ubuntu/Desktop/live/AAC.py &
python3 /home/ubuntu/Desktop/live/AACG.py &
python3 /home/ubuntu/Desktop/live/AACI.py &
python3 /home/ubuntu/Desktop/live/AACIU.py &
python3 /home/ubuntu/Desktop/live/AACIW.py &
python3 /home/ubuntu/Desktop/live/AADI.py &
python3 /home/ubuntu/Desktop/live/AAIC.py &
python3 /home/ubuntu/Desktop/live/AAL.py &
python3 /home/ubuntu/Desktop/live/AAMC.py &
python3 /home/ubuntu/Desktop/live/AAME.py &
python3 /home/ubuntu/Desktop/live/AAN.py &
python3 /home/ubuntu/Desktop/live/AAOI.py &
python3 /home/ubuntu/Desktop/live/AAON.py &
python3 /home/ubuntu/Desktop/live/AAP.py &
python3 /home/ubuntu/Desktop/live/AAPL.py &
python3 /home/ubuntu/Desktop/live/AAQC.py &
python3 /home/ubuntu/Desktop/live/AAT.py &
python3 /home/ubuntu/Desktop/live/AATC.py &
python3 /home/ubuntu/Desktop/live/AAU.py &
python3 /home/ubuntu/Desktop/live/AAWW.py &
python3 /home/ubuntu/Desktop/live/AB.py &
python3 /home/ubuntu/Desktop/live/ABB.py &
python3 /home/ubuntu/Desktop/live/ABBV.py &
python3 /home/ubuntu/Desktop/live/ABC.py &
python3 /home/ubuntu/Desktop/live/ABCB.py &
python3 /home/ubuntu/Desktop/live/ABCL.py &
python3 /home/ubuntu/Desktop/live/ABCM.py &
python3 /home/ubuntu/Desktop/live/ABEO.py &
python3 /home/ubuntu/Desktop/live/ABEV.py &
python3 /home/ubuntu/Desktop/live/ABG.py &
python3 /home/ubuntu/Desktop/live/ABGI.py &
python3 /home/ubuntu/Desktop/live/ABIO.py &
python3 /home/ubuntu/Desktop/live/ABM.py &
python3 /home/ubuntu/Desktop/live/ABMD.py &
python3 /home/ubuntu/Desktop/live/ABNB.py &
python3 /home/ubuntu/Desktop/live/ABOS.py &
python3 /home/ubuntu/Desktop/live/ABR.py &
python3 /home/ubuntu/Desktop/live/ABSI.py &
python3 /home/ubuntu/Desktop/live/ABST.py &
python3 /home/ubuntu/Desktop/live/ABT.py &
python3 /home/ubuntu/Desktop/live/ABTX.py &
python3 /home/ubuntu/Desktop/live/ABUS.py &
python3 /home/ubuntu/Desktop/live/ABVC.py &
python3 /home/ubuntu/Desktop/live/AC.py &
python3 /home/ubuntu/Desktop/live/ACA.py &
python3 /home/ubuntu/Desktop/live/ACAB.py &
python3 /home/ubuntu/Desktop/live/ACABU.py &
python3 /home/ubuntu/Desktop/live/ACAD.py &
python3 /home/ubuntu/Desktop/live/ACAH.py &
python3 /home/ubuntu/Desktop/live/ACAHU.py &
python3 /home/ubuntu/Desktop/live/ACAHW.py &
python3 /home/ubuntu/Desktop/live/ACAQ.py &
python3 /home/ubuntu/Desktop/live/ACAXR.py &
python3 /home/ubuntu/Desktop/live/ACAXU.py &
python3 /home/ubuntu/Desktop/live/ACAXW.py &
python3 /home/ubuntu/Desktop/live/ACEL.py &
python3 /home/ubuntu/Desktop/live/ACER.py &
python3 /home/ubuntu/Desktop/live/ACET.py &
python3 /home/ubuntu/Desktop/live/ACEV.py &
python3 /home/ubuntu/Desktop/live/ACEVU.py &
python3 /home/ubuntu/Desktop/live/ACGL.py &
python3 /home/ubuntu/Desktop/live/ACGLN.py &
python3 /home/ubuntu/Desktop/live/ACGLO.py &
python3 /home/ubuntu/Desktop/live/ACH.py &
python3 /home/ubuntu/Desktop/live/ACHC.py &
python3 /home/ubuntu/Desktop/live/ACHL.py &
python3 /home/ubuntu/Desktop/live/ACHR.py &
python3 /home/ubuntu/Desktop/live/ACHV.py &
python3 /home/ubuntu/Desktop/live/ACI.py &
python3 /home/ubuntu/Desktop/live/ACII.py &
python3 /home/ubuntu/Desktop/live/ACIU.py &
python3 /home/ubuntu/Desktop/live/ACIW.py &
python3 /home/ubuntu/Desktop/live/ACM.py &
python3 /home/ubuntu/Desktop/live/ACMR.py &
python3 /home/ubuntu/Desktop/live/ACN.py &
python3 /home/ubuntu/Desktop/live/ACNB.py &
python3 /home/ubuntu/Desktop/live/ACON.py &
python3 /home/ubuntu/Desktop/live/ACONW.py &
python3 /home/ubuntu/Desktop/live/ACOR.py &
python3 /home/ubuntu/Desktop/live/ACP.py &
python3 /home/ubuntu/Desktop/live/ACQR.py &
python3 /home/ubuntu/Desktop/live/ACQRU.py &
python3 /home/ubuntu/Desktop/live/ACR.py &
python3 /home/ubuntu/Desktop/live/ACRO.py &
python3 /home/ubuntu/Desktop/live/ACRS.py &
python3 /home/ubuntu/Desktop/live/ACRX.py &
python3 /home/ubuntu/Desktop/live/ACST.py &
python3 /home/ubuntu/Desktop/live/ACT.py &
python3 /home/ubuntu/Desktop/live/ACTD.py &
python3 /home/ubuntu/Desktop/live/ACU.py &
python3 /home/ubuntu/Desktop/live/ACV.py &
python3 /home/ubuntu/Desktop/live/ACVA.py &
python3 /home/ubuntu/Desktop/live/ACXP.py &
python3 /home/ubuntu/Desktop/live/ADAG.py &
python3 /home/ubuntu/Desktop/live/ADAL.py &
python3 /home/ubuntu/Desktop/live/ADAP.py &
python3 /home/ubuntu/Desktop/live/ADBE.py &
python3 /home/ubuntu/Desktop/live/ADC.py &
python3 /home/ubuntu/Desktop/live/ADCT.py &
python3 /home/ubuntu/Desktop/live/ADER.py &
python3 /home/ubuntu/Desktop/live/ADERW.py &
python3 /home/ubuntu/Desktop/live/ADES.py &
python3 /home/ubuntu/Desktop/live/ADEX.py &
python3 /home/ubuntu/Desktop/live/ADGI.py &
python3 /home/ubuntu/Desktop/live/ADI.py &
python3 /home/ubuntu/Desktop/live/ADIL.py &
python3 /home/ubuntu/Desktop/live/ADM.py &
python3 /home/ubuntu/Desktop/live/ADMA.py &
python3 /home/ubuntu/Desktop/live/ADMP.py &
python3 /home/ubuntu/Desktop/live/ADN.py &
python3 /home/ubuntu/Desktop/live/ADNT.py &
python3 /home/ubuntu/Desktop/live/ADOC.py &
python3 /home/ubuntu/Desktop/live/ADOCR.py &
python3 /home/ubuntu/Desktop/live/ADOCW.py &
python3 /home/ubuntu/Desktop/live/ADP.py &
python3 /home/ubuntu/Desktop/live/ADPT.py &
python3 /home/ubuntu/Desktop/live/ADRA.py &
python3 /home/ubuntu/Desktop/live/ADRT.py &
python3 /home/ubuntu/Desktop/live/ADSE.py &
python3 /home/ubuntu/Desktop/live/ADSEW.py &
python3 /home/ubuntu/Desktop/live/ADSK.py &
python3 /home/ubuntu/Desktop/live/ADT.py &
python3 /home/ubuntu/Desktop/live/ADTH.py &
python3 /home/ubuntu/Desktop/live/ADTHW.py &
python3 /home/ubuntu/Desktop/live/ADTN.py &
python3 /home/ubuntu/Desktop/live/ADTX.py &
python3 /home/ubuntu/Desktop/live/ADUS.py &
python3 /home/ubuntu/Desktop/live/ADV.py &
python3 /home/ubuntu/Desktop/live/ADVM.py &
python3 /home/ubuntu/Desktop/live/ADX.py &
python3 /home/ubuntu/Desktop/live/ADXN.py &
python3 /home/ubuntu/Desktop/live/AE.py &
python3 /home/ubuntu/Desktop/live/AEAC.py &
python3 /home/ubuntu/Desktop/live/AEE.py &
python3 /home/ubuntu/Desktop/live/AEF.py &
python3 /home/ubuntu/Desktop/live/AEFC.py &
python3 /home/ubuntu/Desktop/live/AEG.py &
python3 /home/ubuntu/Desktop/live/AEI.py &
python3 /home/ubuntu/Desktop/live/AEIS.py &
python3 /home/ubuntu/Desktop/live/AEL.py &
python3 /home/ubuntu/Desktop/live/AEM.py &
python3 /home/ubuntu/Desktop/live/AEMD.py &
python3 /home/ubuntu/Desktop/live/AENZ.py &
python3 /home/ubuntu/Desktop/live/AEO.py &
python3 /home/ubuntu/Desktop/live/AEP.py &
python3 /home/ubuntu/Desktop/live/AEPPZ.py &
python3 /home/ubuntu/Desktop/live/AER.py &
python3 /home/ubuntu/Desktop/live/AERC.py &
python3 /home/ubuntu/Desktop/live/AERI.py &
python3 /home/ubuntu/Desktop/live/AES.py &
python3 /home/ubuntu/Desktop/live/AESC.py &
python3 /home/ubuntu/Desktop/live/AESC.py &
python3 /home/ubuntu/Desktop/live/AEVA.py &
python3 /home/ubuntu/Desktop/live/AESE.py &
python3 /home/ubuntu/Desktop/live/AEY.py &
python3 /home/ubuntu/Desktop/live/AEYE.py &
python3 /home/ubuntu/Desktop/live/AEZS.py &
python3 /home/ubuntu/Desktop/live/AFAC.py &
python3 /home/ubuntu/Desktop/live/AFACW.py &
python3 /home/ubuntu/Desktop/live/AFAQ.py &
python3 /home/ubuntu/Desktop/live/AFAQU.py &
python3 /home/ubuntu/Desktop/live/AFAQW.py &
python3 /home/ubuntu/Desktop/live/AFB.py &
python3 /home/ubuntu/Desktop/live/AFBI.py &
python3 /home/ubuntu/Desktop/live/AFCG.py &
python3 /home/ubuntu/Desktop/live/AFG.py &
python3 /home/ubuntu/Desktop/live/AFGB.py &
python3 /home/ubuntu/Desktop/live/AFGC.py &
python3 /home/ubuntu/Desktop/live/AFGD.py &
python3 /home/ubuntu/Desktop/live/AFGE.py &
python3 /home/ubuntu/Desktop/live/AFI.py &
python3 /home/ubuntu/Desktop/live/AFIB.py &
python3 /home/ubuntu/Desktop/live/AFL.py &
python3 /home/ubuntu/Desktop/live/AFMD.py &
python3 /home/ubuntu/Desktop/live/AFRM.py &
python3 /home/ubuntu/Desktop/live/AFT.py &
python3 /home/ubuntu/Desktop/live/AFTR.py &
python3 /home/ubuntu/Desktop/live/AFYA.py &
python3 /home/ubuntu/Desktop/live/AG.py &
python3 /home/ubuntu/Desktop/live/AGAC.py &
python3 /home/ubuntu/Desktop/live/AGBA.py &
python3 /home/ubuntu/Desktop/live/AGBAR.py &
python3 /home/ubuntu/Desktop/live/AGBAW.py &
python3 /home/ubuntu/Desktop/live/AGCB.py &
python3 /home/ubuntu/Desktop/live/AGCO.py &
python3 /home/ubuntu/Desktop/live/AGD.py &
python3 /home/ubuntu/Desktop/live/AGE.py &
python3 /home/ubuntu/Desktop/live/AGEN.py &
python3 /home/ubuntu/Desktop/live/AGFS.py &
python3 /home/ubuntu/Desktop/live/AGFY.py &
python3 /home/ubuntu/Desktop/live/AGGR.py &
python3 /home/ubuntu/Desktop/live/AGGRU.py &
python3 /home/ubuntu/Desktop/live/AGI.py &
python3 /home/ubuntu/Desktop/live/AGIL.py &
python3 /home/ubuntu/Desktop/live/AGILW.py &
python3 /home/ubuntu/Desktop/live/AGIO.py &
python3 /home/ubuntu/Desktop/live/AGL.py &
python3 /home/ubuntu/Desktop/live/AGLE.py &
python3 /home/ubuntu/Desktop/live/AGM.py &
python3 /home/ubuntu/Desktop/live/AGMH.py &
python3 /home/ubuntu/Desktop/live/AGNC.py &
python3 /home/ubuntu/Desktop/live/AGNCM.py &
python3 /home/ubuntu/Desktop/live/AGNCN.py &
python3 /home/ubuntu/Desktop/live/AGNCO.py &
python3 /home/ubuntu/Desktop/live/AGNCP.py &
python3 /home/ubuntu/Desktop/live/AGO.py &
python3 /home/ubuntu/Desktop/live/AGR.py &
python3 /home/ubuntu/Desktop/live/AGRI.py &
python3 /home/ubuntu/Desktop/live/AGRIW.py &
python3 /home/ubuntu/Desktop/live/AGRO.py &
python3 /home/ubuntu/Desktop/live/AGRX.py &
python3 /home/ubuntu/Desktop/live/AGS.py &
python3 /home/ubuntu/Desktop/live/AGTC.py &
python3 /home/ubuntu/Desktop/live/AGTI.py &
python3 /home/ubuntu/Desktop/live/AGX.py &
python3 /home/ubuntu/Desktop/live/AGYS.py &
python3 /home/ubuntu/Desktop/live/AHCO.py &
python3 /home/ubuntu/Desktop/live/AHG.py &
python3 /home/ubuntu/Desktop/live/AHH.py &
python3 /home/ubuntu/Desktop/live/AHI.py &
python3 /home/ubuntu/Desktop/live/AHPA.py &
python3 /home/ubuntu/Desktop/live/AHPAU.py &
python3 /home/ubuntu/Desktop/live/AHPAW.py &
python3 /home/ubuntu/Desktop/live/AHPI.py &
python3 /home/ubuntu/Desktop/live/AHRN.py &
python3 /home/ubuntu/Desktop/live/AHRNU.py &
python3 /home/ubuntu/Desktop/live/AHT.py &
python3 /home/ubuntu/Desktop/live/AI.py &
python3 /home/ubuntu/Desktop/live/AIB.py &
python3 /home/ubuntu/Desktop/live/AIC.py &
python3 /home/ubuntu/Desktop/live/AIF.py &
python3 /home/ubuntu/Desktop/live/AIG.py &
python3 /home/ubuntu/Desktop/live/AIH.py &
python3 /home/ubuntu/Desktop/live/AIHS.py &
python3 /home/ubuntu/Desktop/live/AIKI.py &
python3 /home/ubuntu/Desktop/live/AIM.py &
python3 /home/ubuntu/Desktop/live/AIMAU.py &
python3 /home/ubuntu/Desktop/live/AIMC.py &
python3 /home/ubuntu/Desktop/live/AIN.py &
python3 /home/ubuntu/Desktop/live/AINC.py &
python3 /home/ubuntu/Desktop/live/AINV.py &
python3 /home/ubuntu/Desktop/live/AIO.py &
python3 /home/ubuntu/Desktop/live/AIO.py &
python3 /home/ubuntu/Desktop/live/AIP.py &
python3 /home/ubuntu/Desktop/live/AIR.py &
python3 /home/ubuntu/Desktop/live/AIRC.py &
python3 /home/ubuntu/Desktop/live/AIRG.py &
python3 /home/ubuntu/Desktop/live/AIRI.py &
python3 /home/ubuntu/Desktop/live/AIRS.py &
python3 /home/ubuntu/Desktop/live/AIRT.py &
python3 /home/ubuntu/Desktop/live/AIRTP.py &
python3 /home/ubuntu/Desktop/live/AIT.py &
python3 /home/ubuntu/Desktop/live/AIU.py &
python3 /home/ubuntu/Desktop/live/AIV.py &
python3 /home/ubuntu/Desktop/live/AIZ.py &
python3 /home/ubuntu/Desktop/live/AIZN.py &
python3 /home/ubuntu/Desktop/live/AJG.py &
python3 /home/ubuntu/Desktop/live/AJRD.py &
python3 /home/ubuntu/Desktop/live/AJX.py &
python3 /home/ubuntu/Desktop/live/AJXA.py &
python3 /home/ubuntu/Desktop/live/AKA.py &
python3 /home/ubuntu/Desktop/live/AKAM.py &
python3 /home/ubuntu/Desktop/live/AKAN.py &
python3 /home/ubuntu/Desktop/live/AKBA.py &
python3 /home/ubuntu/Desktop/live/AKIC.py &
python3 /home/ubuntu/Desktop/live/AKR.py &
python3 /home/ubuntu/Desktop/live/AKRO.py &
python3 /home/ubuntu/Desktop/live/AKTS.py &
python3 /home/ubuntu/Desktop/live/AKTX.py &
python3 /home/ubuntu/Desktop/live/AKU.py &
python3 /home/ubuntu/Desktop/live/AKUS.py &
python3 /home/ubuntu/Desktop/live/AKYA.py &
python3 /home/ubuntu/Desktop/live/ALB.py &
python3 /home/ubuntu/Desktop/live/ALBO.py &
python3 /home/ubuntu/Desktop/live/ALC.py &
python3 /home/ubuntu/Desktop/live/ALCC.py &
python3 /home/ubuntu/Desktop/live/ALCO.py &
python3 /home/ubuntu/Desktop/live/ALDX.py &
python3 /home/ubuntu/Desktop/live/ALE.py &
python3 /home/ubuntu/Desktop/live/ALEC.py &
python3 /home/ubuntu/Desktop/live/ALEX.py &
python3 /home/ubuntu/Desktop/live/ALF.py &
python3 /home/ubuntu/Desktop/live/ALFIW.py &
python3 /home/ubuntu/Desktop/live/ALG.py &
python3 /home/ubuntu/Desktop/live/ALGM.py &
python3 /home/ubuntu/Desktop/live/ALGN.py &
python3 /home/ubuntu/Desktop/live/ALGS.py &
python3 /home/ubuntu/Desktop/live/ALGT.py &
python3 /home/ubuntu/Desktop/live/ALHC.py &
python3 /home/ubuntu/Desktop/live/ALIT.py &
python3 /home/ubuntu/Desktop/live/ALJJ.py &
python3 /home/ubuntu/Desktop/live/ALK.py &
python3 /home/ubuntu/Desktop/live/ALKS.py &
python3 /home/ubuntu/Desktop/live/ALLE.py &
python3 /home/ubuntu/Desktop/live/ALLG.py &
python3 /home/ubuntu/Desktop/live/ALLK.py &
python3 /home/ubuntu/Desktop/live/ALLO.py &
python3 /home/ubuntu/Desktop/live/ALLR.py &
python3 /home/ubuntu/Desktop/live/ALLT.py &
python3 /home/ubuntu/Desktop/live/ALLY.py &
python3 /home/ubuntu/Desktop/live/ALNA.py &
python3 /home/ubuntu/Desktop/live/ALNY.py &
python3 /home/ubuntu/Desktop/live/ALOR.py &
python3 /home/ubuntu/Desktop/live/ALORU.py &
python3 /home/ubuntu/Desktop/live/ALORW.py &
python3 /home/ubuntu/Desktop/live/ALOT.py &
python3 /home/ubuntu/Desktop/live/ALPA.py &
python3 /home/ubuntu/Desktop/live/ALPAW.py &
python3 /home/ubuntu/Desktop/live/ALPN.py &
python3 /home/ubuntu/Desktop/live/ALPP.py &
python3 /home/ubuntu/Desktop/live/ALR.py &
python3 /home/ubuntu/Desktop/live/ALRM.py &
python3 /home/ubuntu/Desktop/live/ALRN.py &
python3 /home/ubuntu/Desktop/live/ALRS.py &
python3 /home/ubuntu/Desktop/live/ALSA.py &
python3 /home/ubuntu/Desktop/live/ALSAR.py &
python3 /home/ubuntu/Desktop/live/ALSAW.py &
python3 /home/ubuntu/Desktop/live/ALSN.py &
python3 /home/ubuntu/Desktop/live/ALT.py &
python3 /home/ubuntu/Desktop/live/ALTG.py &
python3 /home/ubuntu/Desktop/live/ALTO.py &
python3 /home/ubuntu/Desktop/live/ALTR.py &
python3 /home/ubuntu/Desktop/live/ALTU.py &
python3 /home/ubuntu/Desktop/live/ALTUU.py &
python3 /home/ubuntu/Desktop/live/ALTUW.py &
python3 /home/ubuntu/Desktop/live/ALV.py &
python3 /home/ubuntu/Desktop/live/ALVR.py &
python3 /home/ubuntu/Desktop/live/ALX.py &
python3 /home/ubuntu/Desktop/live/ALXO.py &
python3 /home/ubuntu/Desktop/live/ALYA.py &
python3 /home/ubuntu/Desktop/live/ALZN.py &
python3 /home/ubuntu/Desktop/live/AM.py &
python3 /home/ubuntu/Desktop/live/AMAL.py &
python3 /home/ubuntu/Desktop/live/AMAM.py &
python3 /home/ubuntu/Desktop/live/AMAO.py &
python3 /home/ubuntu/Desktop/live/AMAOW.py &
python3 /home/ubuntu/Desktop/live/AMAT.py &
python3 /home/ubuntu/Desktop/live/AMBA.py &
python3 /home/ubuntu/Desktop/live/AMBC.py &
python3 /home/ubuntu/Desktop/live/AMBO.py &
python3 /home/ubuntu/Desktop/live/AMBP.py &
python3 /home/ubuntu/Desktop/live/AMC.py &
python3 /home/ubuntu/Desktop/live/AMCI.py &
python3 /home/ubuntu/Desktop/live/AMCIW.py &
python3 /home/ubuntu/Desktop/live/AMCR.py &
python3 /home/ubuntu/Desktop/live/AMCX.py &
python3 /home/ubuntu/Desktop/live/AMD.py &
python3 /home/ubuntu/Desktop/live/AME.py &
python3 /home/ubuntu/Desktop/live/AMED.py &
python3 /home/ubuntu/Desktop/live/AMEH.py &
python3 /home/ubuntu/Desktop/live/AMG.py &
python3 /home/ubuntu/Desktop/live/AMGN.py &
python3 /home/ubuntu/Desktop/live/AMH.py &
python3 /home/ubuntu/Desktop/live/AMK.py &
python3 /home/ubuntu/Desktop/live/AMKR.py &
python3 /home/ubuntu/Desktop/live/AMLX.py &
python3 /home/ubuntu/Desktop/live/AMN.py &
python3 /home/ubuntu/Desktop/live/AMNB.py &
python3 /home/ubuntu/Desktop/live/AMOT.py &
python3 /home/ubuntu/Desktop/live/AMOV.py &
python3 /home/ubuntu/Desktop/live/AMP.py &
python3 /home/ubuntu/Desktop/live/AMPE.py &
python3 /home/ubuntu/Desktop/live/AMPG.py &
python3 /home/ubuntu/Desktop/live/AMPGW.py &
python3 /home/ubuntu/Desktop/live/AMPH.py &
python3 /home/ubuntu/Desktop/live/AMPI.py &
python3 /home/ubuntu/Desktop/live/AMPL.py &
python3 /home/ubuntu/Desktop/live/AMPS.py &
python3 /home/ubuntu/Desktop/live/AMPY.py &
python3 /home/ubuntu/Desktop/live/AMR.py &
python3 /home/ubuntu/Desktop/live/AMRC.py &
python3 /home/ubuntu/Desktop/live/AMRK.py &
python3 /home/ubuntu/Desktop/live/AMRN.py &
python3 /home/ubuntu/Desktop/live/AMRS.py &
python3 /home/ubuntu/Desktop/live/AMRX.py &
python3 /home/ubuntu/Desktop/live/AMS.py &
python3 /home/ubuntu/Desktop/live/AMSC.py &
python3 /home/ubuntu/Desktop/live/AMSF.py &
python3 /home/ubuntu/Desktop/live/AMST.py &
python3 /home/ubuntu/Desktop/live/AMSWA.py &
python3 /home/ubuntu/Desktop/live/AMT.py &
python3 /home/ubuntu/Desktop/live/AMTB.py &
python3 /home/ubuntu/Desktop/live/AMTD.py &
python3 /home/ubuntu/Desktop/live/AMTI.py &
python3 /home/ubuntu/Desktop/live/AMTX.py &
python3 /home/ubuntu/Desktop/live/AMWD.py &
python3 /home/ubuntu/Desktop/live/AMWL.py &
python3 /home/ubuntu/Desktop/live/AMX.py &
python3 /home/ubuntu/Desktop/live/AMYT.py &
python3 /home/ubuntu/Desktop/live/AMZN.py &
python3 /home/ubuntu/Desktop/live/AN.py &
python3 /home/ubuntu/Desktop/live/ANAB.py &
python3 /home/ubuntu/Desktop/live/ANAC.py &
python3 /home/ubuntu/Desktop/live/ANAT.py &
python3 /home/ubuntu/Desktop/live/ANDE.py &
python3 /home/ubuntu/Desktop/live/ANEB.py &
python3 /home/ubuntu/Desktop/live/ANET.py &
python3 /home/ubuntu/Desktop/live/ANF.py &
python3 /home/ubuntu/Desktop/live/ANGH.py &
python3 /home/ubuntu/Desktop/live/ANDE.py &
python3 /home/ubuntu/Desktop/live/ANEB.py &
python3 /home/ubuntu/Desktop/live/ANET.py &
python3 /home/ubuntu/Desktop/live/ANF.py &
python3 /home/ubuntu/Desktop/live/ANGH.py &
python3 /home/ubuntu/Desktop/live/ANGHW.py &
python3 /home/ubuntu/Desktop/live/ANGI.py &
python3 /home/ubuntu/Desktop/live/ANGN.py &
python3 /home/ubuntu/Desktop/live/ANGO.py &
python3 /home/ubuntu/Desktop/live/ANIK.py &
python3 /home/ubuntu/Desktop/live/ANIP.py &
python3 /home/ubuntu/Desktop/live/ANIX.py &
python3 /home/ubuntu/Desktop/live/ANPC.py &
python3 /home/ubuntu/Desktop/live/ANSS.py &
python3 /home/ubuntu/Desktop/live/ANTE.py &
python3 /home/ubuntu/Desktop/live/ANTM.py &
python3 /home/ubuntu/Desktop/live/ANTX.py &
python3 /home/ubuntu/Desktop/live/ANVS.py &
python3 /home/ubuntu/Desktop/live/ANY.py &
python3 /home/ubuntu/Desktop/live/ANZU.py &
python3 /home/ubuntu/Desktop/live/ANZUU.py &
python3 /home/ubuntu/Desktop/live/ANZUW.py &
python3 /home/ubuntu/Desktop/live/AOD.py &
python3 /home/ubuntu/Desktop/live/AOGO.py &
python3 /home/ubuntu/Desktop/live/AOGOW.py &
python3 /home/ubuntu/Desktop/live/AOMR.py &
python3 /home/ubuntu/Desktop/live/AON.py &
python3 /home/ubuntu/Desktop/live/AORT.py &
python3 /home/ubuntu/Desktop/live/AOS.py &
python3 /home/ubuntu/Desktop/live/AOSL.py &
python3 /home/ubuntu/Desktop/live/AOUT.py &
python3 /home/ubuntu/Desktop/live/AP.py &
python3 /home/ubuntu/Desktop/live/APA.py &
python3 /home/ubuntu/Desktop/live/APAC.py &
python3 /home/ubuntu/Desktop/live/APACW.py &
python3 /home/ubuntu/Desktop/live/APAM.py &
python3 /home/ubuntu/Desktop/live/APCA.py &
python3 /home/ubuntu/Desktop/live/APCX.py &
python3 /home/ubuntu/Desktop/live/APCXW.py &
python3 /home/ubuntu/Desktop/live/APD.py &
python3 /home/ubuntu/Desktop/live/APDN.py &
python3 /home/ubuntu/Desktop/live/APEI.py &
python3 /home/ubuntu/Desktop/live/APEN.py &
python3 /home/ubuntu/Desktop/live/APG.py &
python3 /home/ubuntu/Desktop/live/APGB.py &
python3 /home/ubuntu/Desktop/live/APH.py &
python3 /home/ubuntu/Desktop/live/API.py &
python3 /home/ubuntu/Desktop/live/APLD.py &
python3 /home/ubuntu/Desktop/live/APLE.py &
python3 /home/ubuntu/Desktop/live/APLS.py &
python3 /home/ubuntu/Desktop/live/APLT.py &
python3 /home/ubuntu/Desktop/live/APM.py &
python3 /home/ubuntu/Desktop/live/APMI.py &
python3 /home/ubuntu/Desktop/live/APMIU.py &
python3 /home/ubuntu/Desktop/live/APMIW.py &
python3 /home/ubuntu/Desktop/live/APN.py &
python3 /home/ubuntu/Desktop/live/APO.py &
python3 /home/ubuntu/Desktop/live/APOG.py &
python3 /home/ubuntu/Desktop/live/APP.py &
python3 /home/ubuntu/Desktop/live/APPF.py &
python3 /home/ubuntu/Desktop/live/APPH.py &
python3 /home/ubuntu/Desktop/live/APPHW.py &
python3 /home/ubuntu/Desktop/live/APPN.py &
python3 /home/ubuntu/Desktop/live/APPS.py &
python3 /home/ubuntu/Desktop/live/APRE.py &
python3 /home/ubuntu/Desktop/live/APRN.py &
python3 /home/ubuntu/Desktop/live/APSG.py &
python3 /home/ubuntu/Desktop/live/APT.py &
python3 /home/ubuntu/Desktop/live/APTMU.py &
python3 /home/ubuntu/Desktop/live/APTMW.py &
python3 /home/ubuntu/Desktop/live/APTO.py &
python3 /home/ubuntu/Desktop/live/APTS.py &
python3 /home/ubuntu/Desktop/live/APTV.py &
python3 /home/ubuntu/Desktop/live/APTX.py &
python3 /home/ubuntu/Desktop/live/APVO.py &
python3 /home/ubuntu/Desktop/live/APWC.py &
python3 /home/ubuntu/Desktop/live/APXI.py &
python3 /home/ubuntu/Desktop/live/APXIU.py &
python3 /home/ubuntu/Desktop/live/APXIW.py &
python3 /home/ubuntu/Desktop/live/APYX.py &
python3 /home/ubuntu/Desktop/live/AQB.py &
python3 /home/ubuntu/Desktop/live/AQMS.py &
python3 /home/ubuntu/Desktop/live/AQN.py &
python3 /home/ubuntu/Desktop/live/AQNA.py &
python3 /home/ubuntu/Desktop/live/AQNB.py &
python3 /home/ubuntu/Desktop/live/AQNU.py &
python3 /home/ubuntu/Desktop/live/AQST.py &
python3 /home/ubuntu/Desktop/live/AQUA.py &
python3 /home/ubuntu/Desktop/live/AR.py &
python3 /home/ubuntu/Desktop/live/ARAV.py &
python3 /home/ubuntu/Desktop/live/ARAY.py &
python3 /home/ubuntu/Desktop/live/ARBE.py &
python3 /home/ubuntu/Desktop/live/ARBEW.py &
python3 /home/ubuntu/Desktop/live/ARBG.py &
python3 /home/ubuntu/Desktop/live/ARBGU.py &
python3 /home/ubuntu/Desktop/live/ARBGW.py &
python3 /home/ubuntu/Desktop/live/ARBK.py &
python3 /home/ubuntu/Desktop/live/ARC.py &
python3 /home/ubuntu/Desktop/live/ARCB.py &
python3 /home/ubuntu/Desktop/live/ARCC.py &
python3 /home/ubuntu/Desktop/live/ARCE.py &
python3 /home/ubuntu/Desktop/live/ARCH.py &
python3 /home/ubuntu/Desktop/live/ARCK.py &
python3 /home/ubuntu/Desktop/live/ARCKU.py &
python3 /home/ubuntu/Desktop/live/ARCKW.py &
python3 /home/ubuntu/Desktop/live/ARCO.py &
python3 /home/ubuntu/Desktop/live/ARCT.py &
python3 /home/ubuntu/Desktop/live/ARDC.py &
python3 /home/ubuntu/Desktop/live/ARDS.py &
python3 /home/ubuntu/Desktop/live/ARDX.py &
python3 /home/ubuntu/Desktop/live/ARE.py &
python3 /home/ubuntu/Desktop/live/AREB.py &
python3 /home/ubuntu/Desktop/live/AREBW.py &
python3 /home/ubuntu/Desktop/live/AREC.py &
python3 /home/ubuntu/Desktop/live/AREN.py &
python3 /home/ubuntu/Desktop/live/ARES.py &
python3 /home/ubuntu/Desktop/live/ARGD.py &
python3 /home/ubuntu/Desktop/live/ARGO.py &
python3 /home/ubuntu/Desktop/live/ARGU.py &
python3 /home/ubuntu/Desktop/live/ARGUU.py &
python3 /home/ubuntu/Desktop/live/ARGUW.py &
python3 /home/ubuntu/Desktop/live/ARGX.py &
python3 /home/ubuntu/Desktop/live/ARHS.py &
python3 /home/ubuntu/Desktop/live/ARI.py &
python3 /home/ubuntu/Desktop/live/ARIS.py &
python3 /home/ubuntu/Desktop/live/ARIZ.py &
python3 /home/ubuntu/Desktop/live/ARIZR.py &
python3 /home/ubuntu/Desktop/live/ARIZU.py &
python3 /home/ubuntu/Desktop/live/ARIZW.py &
python3 /home/ubuntu/Desktop/live/ARKO.py &
python3 /home/ubuntu/Desktop/live/ARKOW.py &
python3 /home/ubuntu/Desktop/live/ARKR.py &
python3 /home/ubuntu/Desktop/live/ARL.py &
python3 /home/ubuntu/Desktop/live/ARLO.py &
python3 /home/ubuntu/Desktop/live/ARLP.py &
python3 /home/ubuntu/Desktop/live/ARMK.py &
python3 /home/ubuntu/Desktop/live/ARMP.py &
python3 /home/ubuntu/Desktop/live/ARNC.py &
python3 /home/ubuntu/Desktop/live/AROC.py &
python3 /home/ubuntu/Desktop/live/AROW.py &
python3 /home/ubuntu/Desktop/live/ARQQ.py &
python3 /home/ubuntu/Desktop/live/ARQQW.py &
python3 /home/ubuntu/Desktop/live/ARQT.py &
python3 /home/ubuntu/Desktop/live/ARR.py &
python3 /home/ubuntu/Desktop/live/ARRW.py &
python3 /home/ubuntu/Desktop/live/ARRWU.py &
python3 /home/ubuntu/Desktop/live/ARRWW.py &
python3 /home/ubuntu/Desktop/live/ARRY.py &
python3 /home/ubuntu/Desktop/live/ARTE.py &
python3 /home/ubuntu/Desktop/live/ARTEW.py &
python3 /home/ubuntu/Desktop/live/ARTL.py &
python3 /home/ubuntu/Desktop/live/ARTLW.py &
python3 /home/ubuntu/Desktop/live/ARTNA.py &
python3 /home/ubuntu/Desktop/live/ARTW.py &
python3 /home/ubuntu/Desktop/live/ARVL.py &
python3 /home/ubuntu/Desktop/live/ARVN.py &
python3 /home/ubuntu/Desktop/live/ARW.py &
python3 /home/ubuntu/Desktop/live/ARWR.py &
python3 /home/ubuntu/Desktop/live/ARYD.py &
python3 /home/ubuntu/Desktop/live/ARYE.py &
python3 /home/ubuntu/Desktop/live/ASA.py &
python3 /home/ubuntu/Desktop/live/ASAI.py &
python3 /home/ubuntu/Desktop/live/ASAN.py &
python3 /home/ubuntu/Desktop/live/ASAQ.py &
python3 /home/ubuntu/Desktop/live/ASAX.py &
python3 /home/ubuntu/Desktop/live/ASB.py &
python3 /home/ubuntu/Desktop/live/ASC.py &
python3 /home/ubuntu/Desktop/live/ASCA.py &
python3 /home/ubuntu/Desktop/live/ASCAR.py &
python3 /home/ubuntu/Desktop/live/ASCBU.py &
python3 /home/ubuntu/Desktop/live/ASG.py &
python3 /home/ubuntu/Desktop/live/ASGI.py &
python3 /home/ubuntu/Desktop/live/ASGN.py &
python3 /home/ubuntu/Desktop/live/ASH.py &
python3 /home/ubuntu/Desktop/live/ASIX.py &
python3 /home/ubuntu/Desktop/live/ASLE.py &
python3 /home/ubuntu/Desktop/live/ASLN.py &
python3 /home/ubuntu/Desktop/live/ASM.py &
python3 /home/ubuntu/Desktop/live/ASMB.py &
python3 /home/ubuntu/Desktop/live/ASML.py &
python3 /home/ubuntu/Desktop/live/ASND.py &
python3 /home/ubuntu/Desktop/live/ASNS.py &
python3 /home/ubuntu/Desktop/live/ASO.py &
python3 /home/ubuntu/Desktop/live/ASPA.py &
python3 /home/ubuntu/Desktop/live/ASPAU.py &
python3 /home/ubuntu/Desktop/live/ASPAW.py &
python3 /home/ubuntu/Desktop/live/ASPC.py &
python3 /home/ubuntu/Desktop/live/ASPCU.py &
python3 /home/ubuntu/Desktop/live/ASPCW.py &
python3 /home/ubuntu/Desktop/live/ASPN.py &
python3 /home/ubuntu/Desktop/live/ASPS.py &
python3 /home/ubuntu/Desktop/live/ASPU.py &
python3 /home/ubuntu/Desktop/live/ASR.py &
python3 /home/ubuntu/Desktop/live/ASRT.py &
python3 /home/ubuntu/Desktop/live/ASRV.py &
python3 /home/ubuntu/Desktop/live/ASTC.py &
python3 /home/ubuntu/Desktop/live/ASTE.py &
python3 /home/ubuntu/Desktop/live/ASTL.py &
python3 /home/ubuntu/Desktop/live/ASTLW.py &
python3 /home/ubuntu/Desktop/live/ASTR.py &
python3 /home/ubuntu/Desktop/live/ASTS.py &
python3 /home/ubuntu/Desktop/live/ASTSW.py &
python3 /home/ubuntu/Desktop/live/ASUR.py &
python3 /home/ubuntu/Desktop/live/ASX.py &
python3 /home/ubuntu/Desktop/live/ASXC.py 
