clear
python3 /home/ubuntu/Desktop/live2/ASYS.py &
python3 /home/ubuntu/Desktop/live2/ASZ.py &
python3 /home/ubuntu/Desktop/live2/ATA.py &
python3 /home/ubuntu/Desktop/live2/ATAI.py &
python3 /home/ubuntu/Desktop/live2/ATAK.py &
python3 /home/ubuntu/Desktop/live2/ATAKR.py &
python3 /home/ubuntu/Desktop/live2/ATAKU.py &
python3 /home/ubuntu/Desktop/live2/ATAKW.py &
python3 /home/ubuntu/Desktop/live2/ATAQ.py &
python3 /home/ubuntu/Desktop/live2/ATAX.py &
python3 /home/ubuntu/Desktop/live2/ATC.py &
python3 /home/ubuntu/Desktop/live2/ATCO.py &
python3 /home/ubuntu/Desktop/live2/ATCOL.py &
python3 /home/ubuntu/Desktop/live2/ATCX.py &
python3 /home/ubuntu/Desktop/live2/ATEC.py &
python3 /home/ubuntu/Desktop/live2/ATEK.py &
python3 /home/ubuntu/Desktop/live2/ATEN.py &
python3 /home/ubuntu/Desktop/live2/ATER.py &
python3 /home/ubuntu/Desktop/live2/ATEX.py &
python3 /home/ubuntu/Desktop/live2/ATGE.py &
python3 /home/ubuntu/Desktop/live2/ATHE.py &
python3 /home/ubuntu/Desktop/live2/ATHM.py &
python3 /home/ubuntu/Desktop/live2/ATHX.py &
python3 /home/ubuntu/Desktop/live2/ATI.py &
python3 /home/ubuntu/Desktop/live2/ATIF.py &
python3 /home/ubuntu/Desktop/live2/ATIP.py &
python3 /home/ubuntu/Desktop/live2/ATKR.py &
python3 /home/ubuntu/Desktop/live2/ATLC.py &
python3 /home/ubuntu/Desktop/live2/ATLCL.py &
python3 /home/ubuntu/Desktop/live2/ATLCP.py &
python3 /home/ubuntu/Desktop/live2/ATLO.py &
python3 /home/ubuntu/Desktop/live2/ATNF.py &
python3 /home/ubuntu/Desktop/live2/ATNFW.py &
python3 /home/ubuntu/Desktop/live2/ATNI.py &
python3 /home/ubuntu/Desktop/live2/ATNM.py &
python3 /home/ubuntu/Desktop/live2/ATNX.py &
python3 /home/ubuntu/Desktop/live2/ATO.py &
python3 /home/ubuntu/Desktop/live2/ATOM.py &
python3 /home/ubuntu/Desktop/live2/ATOS.py &
python3 /home/ubuntu/Desktop/live2/ATR.py &
python3 /home/ubuntu/Desktop/live2/ATRA.py &
python3 /home/ubuntu/Desktop/live2/ATRC.py &
python3 /home/ubuntu/Desktop/live2/ATRI.py &
python3 /home/ubuntu/Desktop/live2/ATNFW.py &
python3 /home/ubuntu/Desktop/live2/ATNI.py &
python3 /home/ubuntu/Desktop/live2/ATNM.py &
python3 /home/ubuntu/Desktop/live2/ATNX.py &
python3 /home/ubuntu/Desktop/live2/ATO.py &
python3 /home/ubuntu/Desktop/live2/ATOM.py &
python3 /home/ubuntu/Desktop/live2/ATOS.py &
python3 /home/ubuntu/Desktop/live2/ATR.py &
python3 /home/ubuntu/Desktop/live2/ATRA.py &
python3 /home/ubuntu/Desktop/live2/ATRC.py &
python3 /home/ubuntu/Desktop/live2/ATRI.py &
python3 /home/ubuntu/Desktop/live2/ATRO.py &
python3 /home/ubuntu/Desktop/live2/ATRS.py &
python3 /home/ubuntu/Desktop/live2/ATSG.py &
python3 /home/ubuntu/Desktop/live2/ATTO.py &
python3 /home/ubuntu/Desktop/live2/ATUS.py &
python3 /home/ubuntu/Desktop/live2/ATVC.py &
python3 /home/ubuntu/Desktop/live2/ATVCW.py &
python3 /home/ubuntu/Desktop/live2/ATVI.py &
python3 /home/ubuntu/Desktop/live2/ATXI.py &
python3 /home/ubuntu/Desktop/live2/ATXS.py &
python3 /home/ubuntu/Desktop/live2/ATY.py &
python3 /home/ubuntu/Desktop/live2/AU.py &
python3 /home/ubuntu/Desktop/live2/AUB.py &
python3 /home/ubuntu/Desktop/live2/AUBAP.py &
python3 /home/ubuntu/Desktop/live2/AUBN.py &
python3 /home/ubuntu/Desktop/live2/AUBN.py &
python3 /home/ubuntu/Desktop/live2/AUBAP.py &
python3 /home/ubuntu/Desktop/live2/AUD.py &
python3 /home/ubuntu/Desktop/live2/AUDC.py &
python3 /home/ubuntu/Desktop/live2/AUGX.py &
python3 /home/ubuntu/Desktop/live2/AUID.py &
python3 /home/ubuntu/Desktop/live2/AUMN.py &
python3 /home/ubuntu/Desktop/live2/AUPH.py &
python3 /home/ubuntu/Desktop/live2/AUR.py &
python3 /home/ubuntu/Desktop/live2/AURA.py &
python3 /home/ubuntu/Desktop/live2/AURC.py &
python3 /home/ubuntu/Desktop/live2/AURCU.py &
python3 /home/ubuntu/Desktop/live2/AURCW.py &
python3 /home/ubuntu/Desktop/live2/AUROW.py &
python3 /home/ubuntu/Desktop/live2/AUS.py &
python3 /home/ubuntu/Desktop/live2/AUST.py &
python3 /home/ubuntu/Desktop/live2/AUTL.py &
python3 /home/ubuntu/Desktop/live2/AUTO.py &
python3 /home/ubuntu/Desktop/live2/AUUD.py &
python3 /home/ubuntu/Desktop/live2/AUUDW.py &
python3 /home/ubuntu/Desktop/live2/AUVI.py &
python3 /home/ubuntu/Desktop/live2/AUVIP.py &
python3 /home/ubuntu/Desktop/live2/AUY.py &
python3 /home/ubuntu/Desktop/live2/AUVIP.py &
python3 /home/ubuntu/Desktop/live2/AUY.py &
python3 /home/ubuntu/Desktop/live2/AVA.py &
python3 /home/ubuntu/Desktop/live2/AVAC.py &
python3 /home/ubuntu/Desktop/live2/AVACW.py &
python3 /home/ubuntu/Desktop/live2/AVAH.py &
python3 /home/ubuntu/Desktop/live2/AVAL.py &
python3 /home/ubuntu/Desktop/live2/AVAN.py &
python3 /home/ubuntu/Desktop/live2/AVAV.py &
python3 /home/ubuntu/Desktop/live2/AVB.py &
python3 /home/ubuntu/Desktop/live2/AVCO.py &
python3 /home/ubuntu/Desktop/live2/AVCT.py &
python3 /home/ubuntu/Desktop/live2/AVCTW.py &
python3 /home/ubuntu/Desktop/live2/AVD.py &
python3 /home/ubuntu/Desktop/live2/AVDL.py &
python3 /home/ubuntu/Desktop/live2/AVDX.py &
python3 /home/ubuntu/Desktop/live2/AVEO.py &
python3 /home/ubuntu/Desktop/live2/AVGO.py &
python3 /home/ubuntu/Desktop/live2/AVGOP.py &
python3 /home/ubuntu/Desktop/live2/AVGR.py &
python3 /home/ubuntu/Desktop/live2/AVHI.py &
python3 /home/ubuntu/Desktop/live2/AVHIW.py &
python3 /home/ubuntu/Desktop/live2/AVID.py &
python3 /home/ubuntu/Desktop/live2/AVIR.py &
python3 /home/ubuntu/Desktop/live2/AVK.py &
python3 /home/ubuntu/Desktop/live2/AVLR.py &
python3 /home/ubuntu/Desktop/live2/AVNS.py &
python3 /home/ubuntu/Desktop/live2/AVNT.py &
python3 /home/ubuntu/Desktop/live2/AVNW.py &
python3 /home/ubuntu/Desktop/live2/AVO.py &
python3 /home/ubuntu/Desktop/live2/AVPT.py &
python3 /home/ubuntu/Desktop/live2/AVPTW.py &
python3 /home/ubuntu/Desktop/live2/AVRO.py &
python3 /home/ubuntu/Desktop/live2/AVT.py &
python3 /home/ubuntu/Desktop/live2/AVTE.py &
python3 /home/ubuntu/Desktop/live2/AVTR.py &
python3 /home/ubuntu/Desktop/live2/AVTX.py &
python3 /home/ubuntu/Desktop/live2/AVXL.py &
python3 /home/ubuntu/Desktop/live2/AVY.py &
python3 /home/ubuntu/Desktop/live2/AVYA.py &
python3 /home/ubuntu/Desktop/live2/AWF.py &
python3 /home/ubuntu/Desktop/live2/AWH.py &
python3 /home/ubuntu/Desktop/live2/AWI.py &
python3 /home/ubuntu/Desktop/live2/AWK.py &
python3 /home/ubuntu/Desktop/live2/AWP.py &
python3 /home/ubuntu/Desktop/live2/AWR.py &
python3 /home/ubuntu/Desktop/live2/AWRE.py &
python3 /home/ubuntu/Desktop/live2/AWX.py &
python3 /home/ubuntu/Desktop/live2/AX.py &
python3 /home/ubuntu/Desktop/live2/AXAC.py &
python3 /home/ubuntu/Desktop/live2/AXDX.py &
python3 /home/ubuntu/Desktop/live2/AXGN.py &
python3 /home/ubuntu/Desktop/live2/AXH.py &
python3 /home/ubuntu/Desktop/live2/AXL.py &
python3 /home/ubuntu/Desktop/live2/AXLA.py &
python3 /home/ubuntu/Desktop/live2/AXNX.py &
python3 /home/ubuntu/Desktop/live2/AXNX.py &
python3 /home/ubuntu/Desktop/live2/AXNX.py &
python3 /home/ubuntu/Desktop/live2/AXNX.py &
python3 /home/ubuntu/Desktop/live2/AXON.py &
python3 /home/ubuntu/Desktop/live2/AXP.py &
python3 /home/ubuntu/Desktop/live2/AXR.py &
python3 /home/ubuntu/Desktop/live2/AXS.py &
python3 /home/ubuntu/Desktop/live2/AXSM.py &
python3 /home/ubuntu/Desktop/live2/AXTA.py &
python3 /home/ubuntu/Desktop/live2/AXTI.py &
python3 /home/ubuntu/Desktop/live2/AXU.py &
python3 /home/ubuntu/Desktop/live2/AY.py &
python3 /home/ubuntu/Desktop/live2/AYI.py &
python3 /home/ubuntu/Desktop/live2/AYLA.py &
python3 /home/ubuntu/Desktop/live2/AYRO.py &
python3 /home/ubuntu/Desktop/live2/AYTU.py &
python3 /home/ubuntu/Desktop/live2/AYX.py &
python3 /home/ubuntu/Desktop/live2/AZ.py &
python3 /home/ubuntu/Desktop/live2/AZEK.py &
python3 /home/ubuntu/Desktop/live2/AZN.py &
python3 /home/ubuntu/Desktop/live2/AZO.py &
python3 /home/ubuntu/Desktop/live2/AZPN.py &
python3 /home/ubuntu/Desktop/live2/AZRE.py &
python3 /home/ubuntu/Desktop/live2/AZTA.py &
python3 /home/ubuntu/Desktop/live2/AZUL.py &
python3 /home/ubuntu/Desktop/live2/AZYO.py &
python3 /home/ubuntu/Desktop/live2/AZZ.py &
python3 /home/ubuntu/Desktop/live2/B.py &
python3 /home/ubuntu/Desktop/live2/BA.py &
python3 /home/ubuntu/Desktop/live2/BABA.py &
python3 /home/ubuntu/Desktop/live2/BAC.py &
python3 /home/ubuntu/Desktop/live2/BACA.py &
python3 /home/ubuntu/Desktop/live2/BAFN.py &
python3 /home/ubuntu/Desktop/live2/BAH.py &
python3 /home/ubuntu/Desktop/live2/BALL.py &
python3 /home/ubuntu/Desktop/live2/BAK.py &
python3 /home/ubuntu/Desktop/live2/BALY.py &
python3 /home/ubuntu/Desktop/live2/BAM.py &
python3 /home/ubuntu/Desktop/live2/BAMH.py &
python3 /home/ubuntu/Desktop/live2/BAMI.py &
python3 /home/ubuntu/Desktop/live2/BAMR.py &
python3 /home/ubuntu/Desktop/live2/BANC.py &
python3 /home/ubuntu/Desktop/live2/BAND.py &
python3 /home/ubuntu/Desktop/live2/BANF.py &
python3 /home/ubuntu/Desktop/live2/BANFP.py &
python3 /home/ubuntu/Desktop/live2/BANR.py &
python3 /home/ubuntu/Desktop/live2/BANX.py &
python3 /home/ubuntu/Desktop/live2/BAOS.py &
python3 /home/ubuntu/Desktop/live2/BAP.py &
python3 /home/ubuntu/Desktop/live2/BARK.py &
python3 /home/ubuntu/Desktop/live2/BASE.py &
python3 /home/ubuntu/Desktop/live2/BATL.py &
python3 /home/ubuntu/Desktop/live2/BATRA.py &
python3 /home/ubuntu/Desktop/live2/BATRK.py &
python3 /home/ubuntu/Desktop/live2/BAX.py &
python3 /home/ubuntu/Desktop/live2/BB.py &
python3 /home/ubuntu/Desktop/live2/BBAI.py &
python3 /home/ubuntu/Desktop/live2/BBAR.py &
python3 /home/ubuntu/Desktop/live2/BBBY.py &
python3 /home/ubuntu/Desktop/live2/BBCP.py &
python3 /home/ubuntu/Desktop/live2/BBD.py &
python3 /home/ubuntu/Desktop/live2/BBDC.py &
python3 /home/ubuntu/Desktop/live2/BBDO.py &
python3 /home/ubuntu/Desktop/live2/BBGI.py &
python3 /home/ubuntu/Desktop/live2/BBI.py &
python3 /home/ubuntu/Desktop/live2/BBIG.py &
python3 /home/ubuntu/Desktop/live2/BBIGV.py &
python3 /home/ubuntu/Desktop/live2/BBIO.py &
python3 /home/ubuntu/Desktop/live2/BBLG.py &
python3 /home/ubuntu/Desktop/live2/BBLGW.py &
python3 /home/ubuntu/Desktop/live2/BBLN.py &
python3 /home/ubuntu/Desktop/live2/BBN.py &
python3 /home/ubuntu/Desktop/live2/BBQ.py &
python3 /home/ubuntu/Desktop/live2/BBSI.py &
python3 /home/ubuntu/Desktop/live2/BBU.py &
python3 /home/ubuntu/Desktop/live2/BBUC.py &
python3 /home/ubuntu/Desktop/live2/BBVA.py &
python3 /home/ubuntu/Desktop/live2/BBW.py &
python3 /home/ubuntu/Desktop/live2/BBY.py &
python3 /home/ubuntu/Desktop/live2/BBWI.py &
python3 /home/ubuntu/Desktop/live2/BC.py &
python3 /home/ubuntu/Desktop/live2/BCAB.py &
python3 /home/ubuntu/Desktop/live2/BCAC.py &
python3 /home/ubuntu/Desktop/live2/BCACU.py &
python3 /home/ubuntu/Desktop/live2/BCACW.py &
python3 /home/ubuntu/Desktop/live2/BCAT.py &
python3 /home/ubuntu/Desktop/live2/BCBP.py &
python3 /home/ubuntu/Desktop/live2/BCC.py &
python3 /home/ubuntu/Desktop/live2/BCDA.py &
python3 /home/ubuntu/Desktop/live2/BCE.py &
python3 /home/ubuntu/Desktop/live2/BCEL.py &
python3 /home/ubuntu/Desktop/live2/BCH.py &
python3 /home/ubuntu/Desktop/live2/BCLI.py &
python3 /home/ubuntu/Desktop/live2/BCML.py &
python3 /home/ubuntu/Desktop/live2/BCO.py &
python3 /home/ubuntu/Desktop/live2/BCOR.py &
python3 /home/ubuntu/Desktop/live2/BCOV.py &
python3 /home/ubuntu/Desktop/live2/BCOW.py &
python3 /home/ubuntu/Desktop/live2/BCPC.py &
python3 /home/ubuntu/Desktop/live2/BCRX.py &
python3 /home/ubuntu/Desktop/live2/BCS.py &
python3 /home/ubuntu/Desktop/live2/BCSA.py &
python3 /home/ubuntu/Desktop/live2/BCSAU.py &
python3 /home/ubuntu/Desktop/live2/BCSAW.py &
python3 /home/ubuntu/Desktop/live2/BCSF.py &
python3 /home/ubuntu/Desktop/live2/BCTX.py &
python3 /home/ubuntu/Desktop/live2/BCTXW.py &
python3 /home/ubuntu/Desktop/live2/BCV.py &
python3 /home/ubuntu/Desktop/live2/BCX.py &
python3 /home/ubuntu/Desktop/live2/BCYC.py &
python3 /home/ubuntu/Desktop/live2/BDC.py &
python3 /home/ubuntu/Desktop/live2/BDJ.py &
python3 /home/ubuntu/Desktop/live2/BDL.py &
python3 /home/ubuntu/Desktop/live2/BDN.py &
python3 /home/ubuntu/Desktop/live2/BDR.py &
python3 /home/ubuntu/Desktop/live2/BDSX.py &
python3 /home/ubuntu/Desktop/live2/BDTX.py &
python3 /home/ubuntu/Desktop/live2/BDX.py &
python3 /home/ubuntu/Desktop/live2/BDXB.py &
python3 /home/ubuntu/Desktop/live2/BEAM.py &
python3 /home/ubuntu/Desktop/live2/BE.py &
python3 /home/ubuntu/Desktop/live2/BEAT.py &
python3 /home/ubuntu/Desktop/live2/BECN.py &
python3 /home/ubuntu/Desktop/live2/BEDU.py &
python3 /home/ubuntu/Desktop/live2/BEEM.py &
python3 /home/ubuntu/Desktop/live2/BEEMW.py &
python3 /home/ubuntu/Desktop/live2/BEKE.py &
python3 /home/ubuntu/Desktop/live2/BELFA.py &
python3 /home/ubuntu/Desktop/live2/BELFB.py &
python3 /home/ubuntu/Desktop/live2/BEN.py &
python3 /home/ubuntu/Desktop/live2/BENE.py &
python3 /home/ubuntu/Desktop/live2/BENER.py &
python3 /home/ubuntu/Desktop/live2/BENEW.py &
python3 /home/ubuntu/Desktop/live2/BEP.py &
python3 /home/ubuntu/Desktop/live2/BFAM.py &
python3 /home/ubuntu/Desktop/live2/BFC.py &
python3 /home/ubuntu/Desktop/live2/BFH.py &
python3 /home/ubuntu/Desktop/live2/BFI.py &
python3 /home/ubuntu/Desktop/live2/BFIIW.py &
python3 /home/ubuntu/Desktop/live2/BFIN.py &
python3 /home/ubuntu/Desktop/live2/BFK.py &
python3 /home/ubuntu/Desktop/live2/BFLY.py &
python3 /home/ubuntu/Desktop/live2/BFRI.py &
python3 /home/ubuntu/Desktop/live2/BFRIW.py &
python3 /home/ubuntu/Desktop/live2/BFS.py &
python3 /home/ubuntu/Desktop/live2/BEPC.py &
python3 /home/ubuntu/Desktop/live2/BEPH.py &
python3 /home/ubuntu/Desktop/live2/BEPI.py &
python3 /home/ubuntu/Desktop/live2/BERY.py &
python3 /home/ubuntu/Desktop/live2/BEST.py &
python3 /home/ubuntu/Desktop/live2/BFAC.py &
python3 /home/ubuntu/Desktop/live2/BFST.py &
python3 /home/ubuntu/Desktop/live2/BFZ.py &
python3 /home/ubuntu/Desktop/live2/BG.py &
python3 /home/ubuntu/Desktop/live2/BGB.py &
python3 /home/ubuntu/Desktop/live2/BGCP.py &
python3 /home/ubuntu/Desktop/live2/BGFV.py &
python3 /home/ubuntu/Desktop/live2/BGH.py &
python3 /home/ubuntu/Desktop/live2/BGI.py &
python3 /home/ubuntu/Desktop/live2/BGNE.py &
python3 /home/ubuntu/Desktop/live2/BGR.py &
python3 /home/ubuntu/Desktop/live2/BGRY.py &
python3 /home/ubuntu/Desktop/live2/BGRYW.py &
python3 /home/ubuntu/Desktop/live2/BGS.py &
python3 /home/ubuntu/Desktop/live2/BGSF.py &
python3 /home/ubuntu/Desktop/live2/BGSX.py &
python3 /home/ubuntu/Desktop/live2/BGT.py &
python3 /home/ubuntu/Desktop/live2/BGX.py &
python3 /home/ubuntu/Desktop/live2/BGXX.py &
python3 /home/ubuntu/Desktop/live2/BGY.py &
python3 /home/ubuntu/Desktop/live2/BH.py &
python3 /home/ubuntu/Desktop/live2/BHACU.py &
python3 /home/ubuntu/Desktop/live2/BHACW.py &
python3 /home/ubuntu/Desktop/live2/BHAT.py &
python3 /home/ubuntu/Desktop/live2/BHB.py &
python3 /home/ubuntu/Desktop/live2/BHC.py &
python3 /home/ubuntu/Desktop/live2/BHE.py &
python3 /home/ubuntu/Desktop/live2/BHF.py &
python3 /home/ubuntu/Desktop/live2/BHFAL.py &
python3 /home/ubuntu/Desktop/live2/BHFAM.py &
python3 /home/ubuntu/Desktop/live2/BHFAN.py &
python3 /home/ubuntu/Desktop/live2/BHFAO.py &
python3 /home/ubuntu/Desktop/live2/BHFAP.py &
python3 /home/ubuntu/Desktop/live2/BHG.py &
python3 /home/ubuntu/Desktop/live2/BHIL.py &
python3 /home/ubuntu/Desktop/live2/BHK.py &
python3 /home/ubuntu/Desktop/live2/BHLB.py &
python3 /home/ubuntu/Desktop/live2/BHR.py &
python3 /home/ubuntu/Desktop/live2/BHP.py &
python3 /home/ubuntu/Desktop/live2/BHSE.py &
python3 /home/ubuntu/Desktop/live2/BHSEU.py &
python3 /home/ubuntu/Desktop/live2/BHSEW.py &
python3 /home/ubuntu/Desktop/live2/BHV.py &
python3 /home/ubuntu/Desktop/live2/BHVN.py &
python3 /home/ubuntu/Desktop/live2/BIDU.py &
python3 /home/ubuntu/Desktop/live2/BIG.py &
python3 /home/ubuntu/Desktop/live2/BIGC.py &
python3 /home/ubuntu/Desktop/live2/BIGZ.py &
python3 /home/ubuntu/Desktop/live2/BIIB.py &
python3 /home/ubuntu/Desktop/live2/BILI.py &
python3 /home/ubuntu/Desktop/live2/BILL.py &
python3 /home/ubuntu/Desktop/live2/BIMI.py &
python3 /home/ubuntu/Desktop/live2/BIO.py &
python3 /home/ubuntu/Desktop/live2/BIOC.py &
python3 /home/ubuntu/Desktop/live2/BIOL.py &
python3 /home/ubuntu/Desktop/live2/BIOR.py &
python3 /home/ubuntu/Desktop/live2/BIOS.py &
python3 /home/ubuntu/Desktop/live2/BIOSU.py &
python3 /home/ubuntu/Desktop/live2/BIOSW.py &
python3 /home/ubuntu/Desktop/live2/BIOT.py &
python3 /home/ubuntu/Desktop/live2/BIOTU.py &
python3 /home/ubuntu/Desktop/live2/BIOTW.py &
python3 /home/ubuntu/Desktop/live2/BIOX.py &
python3 /home/ubuntu/Desktop/live2/BIP.py &
python3 /home/ubuntu/Desktop/live2/BIPC.py &
python3 /home/ubuntu/Desktop/live2/BIPH.py &
python3 /home/ubuntu/Desktop/live2/BIPI.py &
python3 /home/ubuntu/Desktop/live2/BIRD.py &
python3 /home/ubuntu/Desktop/live2/BIT.py &
python3 /home/ubuntu/Desktop/live2/BITE.py &
python3 /home/ubuntu/Desktop/live2/BITF.py &
python3 /home/ubuntu/Desktop/live2/BJ.py &
python3 /home/ubuntu/Desktop/live2/BJDX.py &
python3 /home/ubuntu/Desktop/live2/BJRI.py &
python3 /home/ubuntu/Desktop/live2/BK.py &
python3 /home/ubuntu/Desktop/live2/BKCC.py &
python3 /home/ubuntu/Desktop/live2/BKD.py &
python3 /home/ubuntu/Desktop/live2/BKE.py &
python3 /home/ubuntu/Desktop/live2/BKEP.py &
python3 /home/ubuntu/Desktop/live2/BKEPP.py &
python3 /home/ubuntu/Desktop/live2/BKH.py &
python3 /home/ubuntu/Desktop/live2/BKI.py &
python3 /home/ubuntu/Desktop/live2/BKKT.py &
python3 /home/ubuntu/Desktop/live2/BKN.py &
python3 /home/ubuntu/Desktop/live2/BKNG.py &
python3 /home/ubuntu/Desktop/live2/BKR.py &
python3 /home/ubuntu/Desktop/live2/BKSC.py &
python3 /home/ubuntu/Desktop/live2/BKSY.py &
python3 /home/ubuntu/Desktop/live2/BKT.py &
python3 /home/ubuntu/Desktop/live2/BKTI.py &
python3 /home/ubuntu/Desktop/live2/BKU.py &
python3 /home/ubuntu/Desktop/live2/BKYI.py &
python3 /home/ubuntu/Desktop/live2/BL.py &
python3 /home/ubuntu/Desktop/live2/BLBD.py &
python3 /home/ubuntu/Desktop/live2/BLBX.py &
python3 /home/ubuntu/Desktop/live2/BLCM.py &
python3 /home/ubuntu/Desktop/live2/BLCM.py &
python3 /home/ubuntu/Desktop/live2/BLCO.py &
python3 /home/ubuntu/Desktop/live2/BLCT.py &
python3 /home/ubuntu/Desktop/live2/BLD.py &
python3 /home/ubuntu/Desktop/live2/BLDE.py &
python3 /home/ubuntu/Desktop/live2/BLDEW.py &
python3 /home/ubuntu/Desktop/live2/BLDP.py &
python3 /home/ubuntu/Desktop/live2/BLDR.py &
python3 /home/ubuntu/Desktop/live2/BLE.py &
python3 /home/ubuntu/Desktop/live2/BLEU.py &
python3 /home/ubuntu/Desktop/live2/BLEUR.py &
python3 /home/ubuntu/Desktop/live2/BLEUU.py &
python3 /home/ubuntu/Desktop/live2/BLEUW.py &
python3 /home/ubuntu/Desktop/live2/BLFS.py &
python3 /home/ubuntu/Desktop/live2/BLFY.py &
python3 /home/ubuntu/Desktop/live2/BLI.py &
python3 /home/ubuntu/Desktop/live2/BLIN.py &
python3 /home/ubuntu/Desktop/live2/BLK.py &
python3 /home/ubuntu/Desktop/live2/BLKB.py &
python3 /home/ubuntu/Desktop/live2/BLMN.py &
python3 /home/ubuntu/Desktop/live2/BLND.py &
python3 /home/ubuntu/Desktop/live2/BLNG.py &
python3 /home/ubuntu/Desktop/live2/BLNGU.py &
python3 /home/ubuntu/Desktop/live2/BLNGW.py &
python3 /home/ubuntu/Desktop/live2/BLNK.py &
python3 /home/ubuntu/Desktop/live2/BLNKW.py &
python3 /home/ubuntu/Desktop/live2/BLPH.py &
python3 /home/ubuntu/Desktop/live2/BLRX.py &
python3 /home/ubuntu/Desktop/live2/BLSA.py &
python3 /home/ubuntu/Desktop/live2/BLTE.py &
python3 /home/ubuntu/Desktop/live2/BLTS.py &
python3 /home/ubuntu/Desktop/live2/BLTSU.py &
python3 /home/ubuntu/Desktop/live2/BLTSW.py &
python3 /home/ubuntu/Desktop/live2/BLU.py &
python3 /home/ubuntu/Desktop/live2/BLUA.py &
python3 /home/ubuntu/Desktop/live2/BLUE.py &
python3 /home/ubuntu/Desktop/live2/BLW.py &
python3 /home/ubuntu/Desktop/live2/BLX.py &
python3 /home/ubuntu/Desktop/live2/BLZE.py &
python3 /home/ubuntu/Desktop/live2/BMA.py &
python3 /home/ubuntu/Desktop/live2/BMAC.py &
python3 /home/ubuntu/Desktop/live2/BMAQ.py &
python3 /home/ubuntu/Desktop/live2/BMAQR.py &
python3 /home/ubuntu/Desktop/live2/BMAQU.py &
python3 /home/ubuntu/Desktop/live2/BMAQW.py &
python3 /home/ubuntu/Desktop/live2/BMBL.py &
python3 /home/ubuntu/Desktop/live2/BME.py &
python3 /home/ubuntu/Desktop/live2/BMEA.py &
python3 /home/ubuntu/Desktop/live2/BMEZ.py &
python3 /home/ubuntu/Desktop/live2/BMI.py &
python3 /home/ubuntu/Desktop/live2/BMO.py &
python3 /home/ubuntu/Desktop/live2/BMRA.py &
python3 /home/ubuntu/Desktop/live2/BMRC.py &
python3 /home/ubuntu/Desktop/live2/BMRN.py &
python3 /home/ubuntu/Desktop/live2/BMTX.py &
python3 /home/ubuntu/Desktop/live2/BMY.py &
python3 /home/ubuntu/Desktop/live2/BNED.py &
python3 /home/ubuntu/Desktop/live2/BNFT.py &
python3 /home/ubuntu/Desktop/live2/BNGO.py &
python3 /home/ubuntu/Desktop/live2/BNGOW.py &
python3 /home/ubuntu/Desktop/live2/BNIX.py &
python3 /home/ubuntu/Desktop/live2/BNIXR.py &
python3 /home/ubuntu/Desktop/live2/BNIXW.py &
python3 /home/ubuntu/Desktop/live2/BNNR.py &
python3 /home/ubuntu/Desktop/live2/BNL.py &
python3 /home/ubuntu/Desktop/live2/BNNRU.py &
python3 /home/ubuntu/Desktop/live2/BNNRW.py &
python3 /home/ubuntu/Desktop/live2/BNOX.py &
python3 /home/ubuntu/Desktop/live2/BNR.py &
python3 /home/ubuntu/Desktop/live2/BNS.py &
python3 /home/ubuntu/Desktop/live2/BNSO.py &
python3 /home/ubuntu/Desktop/live2/BNTC.py &
python3 /home/ubuntu/Desktop/live2/BNTX.py &
python3 /home/ubuntu/Desktop/live2/BNY.py &
python3 /home/ubuntu/Desktop/live2/BOAC.py &
python3 /home/ubuntu/Desktop/live2/BOAS.py &
python3 /home/ubuntu/Desktop/live2/BOC.py &
python3 /home/ubuntu/Desktop/live2/BOCN.py &
python3 /home/ubuntu/Desktop/live2/BOCNW.py &
python3 /home/ubuntu/Desktop/live2/BODY.py &
python3 /home/ubuntu/Desktop/live2/BOE.py &
python3 /home/ubuntu/Desktop/live2/BOH.py &
python3 /home/ubuntu/Desktop/live2/BOKF.py &
python3 /home/ubuntu/Desktop/live2/BOLT.py &
python3 /home/ubuntu/Desktop/live2/BON.py &
python3 /home/ubuntu/Desktop/live2/BOOM.py &
python3 /home/ubuntu/Desktop/live2/BOOT.py &
python3 /home/ubuntu/Desktop/live2/BORR.py &
python3 /home/ubuntu/Desktop/live2/BOSC.py &
python3 /home/ubuntu/Desktop/live2/BOTJ.py &
python3 /home/ubuntu/Desktop/live2/BOWL.py &
python3 /home/ubuntu/Desktop/live2/BOX.py &
python3 /home/ubuntu/Desktop/live2/BOXD.py &
python3 /home/ubuntu/Desktop/live2/BOXL.py &
python3 /home/ubuntu/Desktop/live2/BP.py &
python3 /home/ubuntu/Desktop/live2/BPAC.py &
python3 /home/ubuntu/Desktop/live2/BPACW.py &
python3 /home/ubuntu/Desktop/live2/BPMC.py &
python3 /home/ubuntu/Desktop/live2/BPOP.py &
python3 /home/ubuntu/Desktop/live2/BPOPM.py &
python3 /home/ubuntu/Desktop/live2/BPRN.py &
python3 /home/ubuntu/Desktop/live2/BPT.py &
python3 /home/ubuntu/Desktop/live2/BPTH.py &
python3 /home/ubuntu/Desktop/live2/BPTS.py &
python3 /home/ubuntu/Desktop/live2/BPYPM.py &
python3 /home/ubuntu/Desktop/live2/BPYPN.py &
python3 /home/ubuntu/Desktop/live2/BPYPO.py &
python3 /home/ubuntu/Desktop/live2/BPYPP.py &
python3 /home/ubuntu/Desktop/live2/BQ.py &
python3 /home/ubuntu/Desktop/live2/BR.py &
python3 /home/ubuntu/Desktop/live2/BRAC.py &
python3 /home/ubuntu/Desktop/live2/BRAG.py &
python3 /home/ubuntu/Desktop/live2/BRBR.py &
python3 /home/ubuntu/Desktop/live2/BRBS.py &
python3 /home/ubuntu/Desktop/live2/BRC.py &
python3 /home/ubuntu/Desktop/live2/BRCC.py &
python3 /home/ubuntu/Desktop/live2/BRCN.py &
python3 /home/ubuntu/Desktop/live2/BRDG.py &
python3 /home/ubuntu/Desktop/live2/BRDS.py &
python3 /home/ubuntu/Desktop/live2/BREZ.py &
python3 /home/ubuntu/Desktop/live2/BREZR.py &
python3 /home/ubuntu/Desktop/live2/BREZW.py &
python3 /home/ubuntu/Desktop/live2/BRFH.py &
python3 /home/ubuntu/Desktop/live2/BRFS.py &
python3 /home/ubuntu/Desktop/live2/BRG.py &
python3 /home/ubuntu/Desktop/live2/BRID.py &
python3 /home/ubuntu/Desktop/live2/BRIV.py &
python3 /home/ubuntu/Desktop/live2/BRIVU.py &
python3 /home/ubuntu/Desktop/live2/BRIVW.py &
python3 /home/ubuntu/Desktop/live2/BRKH.py &
python3 /home/ubuntu/Desktop/live2/BRKHW.py &
python3 /home/ubuntu/Desktop/live2/BRKL.py &
python3 /home/ubuntu/Desktop/live2/BRKR.py &
python3 /home/ubuntu/Desktop/live2/BRLI.py &
python3 /home/ubuntu/Desktop/live2/BRLIR.py &
python3 /home/ubuntu/Desktop/live2/BRLIW.py &
python3 /home/ubuntu/Desktop/live2/BRLT.py &
python3 /home/ubuntu/Desktop/live2/BRMK.py &
python3 /home/ubuntu/Desktop/live2/BRN.py &
python3 /home/ubuntu/Desktop/live2/BRO.py &
python3 /home/ubuntu/Desktop/live2/BROG.py &
python3 /home/ubuntu/Desktop/live2/BROGW.py &
python3 /home/ubuntu/Desktop/live2/BROS.py &
python3 /home/ubuntu/Desktop/live2/BRP.py &
python3 /home/ubuntu/Desktop/live2/BRPM.py &
python3 /home/ubuntu/Desktop/live2/BRPMU.py &
python3 /home/ubuntu/Desktop/live2/BRPMW.py &
python3 /home/ubuntu/Desktop/live2/BRQS.py &
python3 /home/ubuntu/Desktop/live2/BRSP.py &
python3 /home/ubuntu/Desktop/live2/BRT.py &
python3 /home/ubuntu/Desktop/live2/BRTX.py &
python3 /home/ubuntu/Desktop/live2/BRW.py &
python3 /home/ubuntu/Desktop/live2/BRX.py &
python3 /home/ubuntu/Desktop/live2/BRY.py &
python3 /home/ubuntu/Desktop/live2/BRZE.py &
python3 /home/ubuntu/Desktop/live2/BSAC.py &
python3 /home/ubuntu/Desktop/live2/BSAQ.py &
python3 /home/ubuntu/Desktop/live2/BSBK.py &
python3 /home/ubuntu/Desktop/live2/BSBR.py &
python3 /home/ubuntu/Desktop/live2/BSET.py &
python3 /home/ubuntu/Desktop/live2/BSFC.py &
python3 /home/ubuntu/Desktop/live2/BSGA.py &
python3 /home/ubuntu/Desktop/live2/BSGAR.py &
python3 /home/ubuntu/Desktop/live2/BSGAU.py &
python3 /home/ubuntu/Desktop/live2/BSGM.py &
python3 /home/ubuntu/Desktop/live2/BSIG.py &
python3 /home/ubuntu/Desktop/live2/BSKY.py &
python3 /home/ubuntu/Desktop/live2/BSKYU.py &
python3 /home/ubuntu/Desktop/live2/BSKYW.py &
python3 /home/ubuntu/Desktop/live2/BSL.py &
python3 /home/ubuntu/Desktop/live2/BSM.py &
python3 /home/ubuntu/Desktop/live2/BSMX.py &
python3 /home/ubuntu/Desktop/live2/BSQR.py &
python3 /home/ubuntu/Desktop/live2/BSRR.py &
python3 /home/ubuntu/Desktop/live2/BST.py &
python3 /home/ubuntu/Desktop/live2/BSTZ.py &
python3 /home/ubuntu/Desktop/live2/BSVN.py &
python3 /home/ubuntu/Desktop/live2/BSX.py &
python3 /home/ubuntu/Desktop/live2/BSY.py &
python3 /home/ubuntu/Desktop/live2/BTA.py &
python3 /home/ubuntu/Desktop/live2/BTU.py &
python3 /home/ubuntu/Desktop/live2/BTWN.py &
python3 /home/ubuntu/Desktop/live2/BTWNU.py &
python3 /home/ubuntu/Desktop/live2/BTWNW.py &
python3 /home/ubuntu/Desktop/live2/BTX.py &
python3 /home/ubuntu/Desktop/live2/BTZ.py &
python3 /home/ubuntu/Desktop/live2/BUD.py &
python3 /home/ubuntu/Desktop/live2/BUI.py &
python3 /home/ubuntu/Desktop/live2/BUR.py &
python3 /home/ubuntu/Desktop/live2/BURL.py &
python3 /home/ubuntu/Desktop/live2/BUSE.py &
python3 /home/ubuntu/Desktop/live2/BV.py &
python3 /home/ubuntu/Desktop/live2/BVH.py &
python3 /home/ubuntu/Desktop/live2/BVN.py &
python3 /home/ubuntu/Desktop/live2/BVS.py &
python3 /home/ubuntu/Desktop/live2/BVXV.py &
python3 /home/ubuntu/Desktop/live2/BTAI.py &
python3 /home/ubuntu/Desktop/live2/BTB.py &
python3 /home/ubuntu/Desktop/live2/BTBD.py &
python3 /home/ubuntu/Desktop/live2/BTBDW.py &
python3 /home/ubuntu/Desktop/live2/BTBT.py &
python3 /home/ubuntu/Desktop/live2/BTCM.py &
python3 /home/ubuntu/Desktop/live2/BTCS.py &
python3 /home/ubuntu/Desktop/live2/BTCY.py &
python3 /home/ubuntu/Desktop/live2/BTG.py &
python3 /home/ubuntu/Desktop/live2/BTI.py &
python3 /home/ubuntu/Desktop/live2/BTO.py &
python3 /home/ubuntu/Desktop/live2/BTN.py &
python3 /home/ubuntu/Desktop/live2/BTOG.py &
python3 /home/ubuntu/Desktop/live2/BTT.py &
python3 /home/ubuntu/Desktop/live2/BTTR.py &
python3 /home/ubuntu/Desktop/live2/BTTX.py &
python3 /home/ubuntu/Desktop/live2/BW.py &
python3 /home/ubuntu/Desktop/live2/BWA.py &
python3 /home/ubuntu/Desktop/live2/BWAC.py &
python3 /home/ubuntu/Desktop/live2/BWACU.py &
python3 /home/ubuntu/Desktop/live2/BWACW.py &
python3 /home/ubuntu/Desktop/live2/BWAY.py &
python3 /home/ubuntu/Desktop/live2/BWB.py &
python3 /home/ubuntu/Desktop/live2/BWBBP.py &
python3 /home/ubuntu/Desktop/live2/BWC.py &
python3 /home/ubuntu/Desktop/live2/BWCAU.py &
python3 /home/ubuntu/Desktop/live2/BWEN.py &
python3 /home/ubuntu/Desktop/live2/BWFG.py &
python3 /home/ubuntu/Desktop/live2/BWG.py &
python3 /home/ubuntu/Desktop/live2/BWMN.py &
python3 /home/ubuntu/Desktop/live2/BWMX.py &
python3 /home/ubuntu/Desktop/live2/BWNB.py &
python3 /home/ubuntu/Desktop/live2/BWSN.py &
python3 /home/ubuntu/Desktop/live2/BWV.py &
python3 /home/ubuntu/Desktop/live2/BWXT.py &
python3 /home/ubuntu/Desktop/live2/BX.py &
python3 /home/ubuntu/Desktop/live2/BXC.py &
python3 /home/ubuntu/Desktop/live2/BXMT.py &
python3 /home/ubuntu/Desktop/live2/BXMX.py &
python3 /home/ubuntu/Desktop/live2/BXP.py &
python3 /home/ubuntu/Desktop/live2/BXRX.py &
python3 /home/ubuntu/Desktop/live2/BXSL.py &
python3 /home/ubuntu/Desktop/live2/BY.py &
python3 /home/ubuntu/Desktop/live2/BYD.py &
python3 /home/ubuntu/Desktop/live2/BYFC.py &
python3 /home/ubuntu/Desktop/live2/BYM.py &
python3 /home/ubuntu/Desktop/live2/BYN.py &
python3 /home/ubuntu/Desktop/live2/BYND.py &
python3 /home/ubuntu/Desktop/live2/BYNO.py &
python3 /home/ubuntu/Desktop/live2/BYNOU.py &
python3 /home/ubuntu/Desktop/live2/BYRN.py &
python3 /home/ubuntu/Desktop/live2/BYSI.py &
python3 /home/ubuntu/Desktop/live2/BYTS.py &
python3 /home/ubuntu/Desktop/live2/BZ.py &
python3 /home/ubuntu/Desktop/live2/BZFD.py &
python3 /home/ubuntu/Desktop/live2/BZFDW.py &
python3 /home/ubuntu/Desktop/live2/BZH.py &
python3 /home/ubuntu/Desktop/live2/BZUN.py &
python3 /home/ubuntu/Desktop/live2/C.py &
python3 /home/ubuntu/Desktop/live2/CAAP.py &
python3 /home/ubuntu/Desktop/live2/CAAS.py &
python3 /home/ubuntu/Desktop/live2/CABA.py &
python3 /home/ubuntu/Desktop/live2/CABO.py &
python3 /home/ubuntu/Desktop/live2/CAC.py &
python3 /home/ubuntu/Desktop/live2/CACC.py &
python3 /home/ubuntu/Desktop/live2/CACI.py &
python3 /home/ubuntu/Desktop/live2/CADE.py &
python3 /home/ubuntu/Desktop/live2/CADL.py &
python3 /home/ubuntu/Desktop/live2/CAE.py &
python3 /home/ubuntu/Desktop/live2/CAF.py &
python3 /home/ubuntu/Desktop/live2/CAG.py &
python3 /home/ubuntu/Desktop/live2/CAH.py &
python3 /home/ubuntu/Desktop/live2/CAJ.py &
python3 /home/ubuntu/Desktop/live2/CAKE.py &
python3 /home/ubuntu/Desktop/live2/CAL.py &
python3 /home/ubuntu/Desktop/live2/CALA.py &
python3 /home/ubuntu/Desktop/live2/CALB.py &
python3 /home/ubuntu/Desktop/live2/CALM.py &
python3 /home/ubuntu/Desktop/live2/CALT.py &
python3 /home/ubuntu/Desktop/live2/CALX.py &
python3 /home/ubuntu/Desktop/live2/CAMP.py &
python3 /home/ubuntu/Desktop/live2/CAMT.py &
python3 /home/ubuntu/Desktop/live2/CAN.py &
python3 /home/ubuntu/Desktop/live2/CANF.py &
python3 /home/ubuntu/Desktop/live2/CANG.py &
python3 /home/ubuntu/Desktop/live2/CANO.py &
python3 /home/ubuntu/Desktop/live2/CAPD.py &
python3 /home/ubuntu/Desktop/live2/CAPL.py &
python3 /home/ubuntu/Desktop/live2/CAPR.py &
python3 /home/ubuntu/Desktop/live2/CAR.py &
python3 /home/ubuntu/Desktop/live2/CARA.py &
python3 /home/ubuntu/Desktop/live2/CARE.py &
python3 /home/ubuntu/Desktop/live2/CARG.py &
python3 /home/ubuntu/Desktop/live2/CARR.py &
python3 /home/ubuntu/Desktop/live2/CARS.py &
python3 /home/ubuntu/Desktop/live2/CARV.py &
python3 /home/ubuntu/Desktop/live2/CAS.py &
python3 /home/ubuntu/Desktop/live2/CASA.py &
python3 /home/ubuntu/Desktop/live2/CASH.py &
python3 /home/ubuntu/Desktop/live2/CASI.py &
python3 /home/ubuntu/Desktop/live2/CASS.py &
python3 /home/ubuntu/Desktop/live2/CASY.py &
python3 /home/ubuntu/Desktop/live2/CAT.py &
python3 /home/ubuntu/Desktop/live2/CATC.py &
python3 /home/ubuntu/Desktop/live2/CATO.py &
python3 /home/ubuntu/Desktop/live2/CATY.py &
python3 /home/ubuntu/Desktop/live2/CB.py &
python3 /home/ubuntu/Desktop/live2/CBAN.py &
python3 /home/ubuntu/Desktop/live2/CBAT.py &
python3 /home/ubuntu/Desktop/live2/CBAY.py &
python3 /home/ubuntu/Desktop/live2/CBD.py &
python3 /home/ubuntu/Desktop/live2/CBFV.py &
python3 /home/ubuntu/Desktop/live2/CBH.py &
python3 /home/ubuntu/Desktop/live2/CBIO.py &
python3 /home/ubuntu/Desktop/live2/CBL.py &
python3 /home/ubuntu/Desktop/live2/CBNK.py &
python3 /home/ubuntu/Desktop/live2/CBOE.py &
python3 /home/ubuntu/Desktop/live2/CBOE.py &
python3 /home/ubuntu/Desktop/live2/CBRE.py &
python3 /home/ubuntu/Desktop/live2/CBRG.py &
python3 /home/ubuntu/Desktop/live2/CBRGW.py &
python3 /home/ubuntu/Desktop/live2/CBRL.py &
python3 /home/ubuntu/Desktop/live2/CBSH.py &
python3 /home/ubuntu/Desktop/live2/CBT.py &
python3 /home/ubuntu/Desktop/live2/CBTX.py &
python3 /home/ubuntu/Desktop/live2/CBU.py &
python3 /home/ubuntu/Desktop/live2/CBZ.py &
python3 /home/ubuntu/Desktop/live2/CC.py &
python3 /home/ubuntu/Desktop/live2/CCAI.py &
python3 /home/ubuntu/Desktop/live2/CCAP.py &
python3 /home/ubuntu/Desktop/live2/CCB.py &
python3 /home/ubuntu/Desktop/live2/CCBG.py &
python3 /home/ubuntu/Desktop/live2/CCCC.py &
python3 /home/ubuntu/Desktop/live2/CCCS.py &
python3 /home/ubuntu/Desktop/live2/CCD.py &
python3 /home/ubuntu/Desktop/live2/CCEL.py &
python3 /home/ubuntu/Desktop/live2/CCEP.py &
python3 /home/ubuntu/Desktop/live2/CCF.py &
python3 /home/ubuntu/Desktop/live2/CCI.py &
python3 /home/ubuntu/Desktop/live2/CCJ.py &
python3 /home/ubuntu/Desktop/live2/CCK.py &
python3 /home/ubuntu/Desktop/live2/CCL.py &
python3 /home/ubuntu/Desktop/live2/CCLP.py &
python3 /home/ubuntu/Desktop/live2/CCM.py &
python3 /home/ubuntu/Desktop/live2/CCMP.py &
python3 /home/ubuntu/Desktop/live2/CCNC.py &
python3 /home/ubuntu/Desktop/live2/CCNE.py &
python3 /home/ubuntu/Desktop/live2/CCNEP.py &
python3 /home/ubuntu/Desktop/live2/CCO.py &
python3 /home/ubuntu/Desktop/live2/CCOI.py &
python3 /home/ubuntu/Desktop/live2/CCRD.py &
python3 /home/ubuntu/Desktop/live2/CCRN.py &
python3 /home/ubuntu/Desktop/live2/CCS.py &
python3 /home/ubuntu/Desktop/live2/CCSI.py &
python3 /home/ubuntu/Desktop/live2/CCTS.py &
python3 /home/ubuntu/Desktop/live2/CCU.py &
python3 /home/ubuntu/Desktop/live2/CCV.py &
python3 /home/ubuntu/Desktop/live2/CCVI.py &
python3 /home/ubuntu/Desktop/live2/CCXI.py &
python3 /home/ubuntu/Desktop/live2/CCZ.py &
python3 /home/ubuntu/Desktop/live2/CD.py &
python3 /home/ubuntu/Desktop/live2/CDAK.py &
python3 /home/ubuntu/Desktop/live2/CDAQ.py &
python3 /home/ubuntu/Desktop/live2/CDAQ.py &
python3 /home/ubuntu/Desktop/live2/CDAQW.py &
python3 /home/ubuntu/Desktop/live2/CDAY.py &
python3 /home/ubuntu/Desktop/live2/CDE.py &
python3 /home/ubuntu/Desktop/live2/CDEV.py &
python3 /home/ubuntu/Desktop/live2/CDK.py &
python3 /home/ubuntu/Desktop/live2/CDLX.py &
python3 /home/ubuntu/Desktop/live2/CDMO.py &
python3 /home/ubuntu/Desktop/live2/CDNA.py &
python3 /home/ubuntu/Desktop/live2/CDNS.py &
python3 /home/ubuntu/Desktop/live2/CDR.py &
python3 /home/ubuntu/Desktop/live2/CDRE.py &
python3 /home/ubuntu/Desktop/live2/CDRO.py &
python3 /home/ubuntu/Desktop/live2/CDROW.py &
python3 /home/ubuntu/Desktop/live2/CDTX.py &
python3 /home/ubuntu/Desktop/live2/CDW.py &
python3 /home/ubuntu/Desktop/live2/CDXC.py &
python3 /home/ubuntu/Desktop/live2/CDXS.py &
python3 /home/ubuntu/Desktop/live2/CDZI.py &
python3 /home/ubuntu/Desktop/live2/CDZIP.py &
python3 /home/ubuntu/Desktop/live2/CE.py &
python3 /home/ubuntu/Desktop/live2/CEA.py &
python3 /home/ubuntu/Desktop/live2/CEAD.py &
python3 /home/ubuntu/Desktop/live2/CEADW.py &
python3 /home/ubuntu/Desktop/live2/CECE.py &
python3 /home/ubuntu/Desktop/live2/CEE.py &
python3 /home/ubuntu/Desktop/live2/CEG.py &
python3 /home/ubuntu/Desktop/live2/CEI.py &
python3 /home/ubuntu/Desktop/live2/CEIX.py &
python3 /home/ubuntu/Desktop/live2/CELC.py &
python3 /home/ubuntu/Desktop/live2/CELH.py &
python3 /home/ubuntu/Desktop/live2/CELU.py &
python3 /home/ubuntu/Desktop/live2/CELUW.py &
python3 /home/ubuntu/Desktop/live2/CELZ.py &
python3 /home/ubuntu/Desktop/live2/CEM.py &
python3 /home/ubuntu/Desktop/live2/CEMI.py &
python3 /home/ubuntu/Desktop/live2/CEN.py &
python3 /home/ubuntu/Desktop/live2/CENN.py &
python3 /home/ubuntu/Desktop/live2/CENQ.py &
python3 /home/ubuntu/Desktop/live2/CENQU.py &
python3 /home/ubuntu/Desktop/live2/CENQW.py &
python3 /home/ubuntu/Desktop/live2/CENT.py &
python3 /home/ubuntu/Desktop/live2/CENTA.py &
python3 /home/ubuntu/Desktop/live2/CENX.py &
python3 /home/ubuntu/Desktop/live2/CEPU.py &
python3 /home/ubuntu/Desktop/live2/CEQP.py &
python3 /home/ubuntu/Desktop/live2/CERE.py &
python3 /home/ubuntu/Desktop/live2/CERN.py &
python3 /home/ubuntu/Desktop/live2/CERS.py &
python3 /home/ubuntu/Desktop/live2/CERT.py &
python3 /home/ubuntu/Desktop/live2/CET.py &
python3 /home/ubuntu/Desktop/live2/CETX.py &
python3 /home/ubuntu/Desktop/live2/CETXP.py &
python3 /home/ubuntu/Desktop/live2/CEV.py &
python3 /home/ubuntu/Desktop/live2/CEVA.py &
python3 /home/ubuntu/Desktop/live2/CF.py &
python3 /home/ubuntu/Desktop/live2/CFB.py &
python3 /home/ubuntu/Desktop/live2/CFBK.py &
python3 /home/ubuntu/Desktop/live2/CFFEU.py &
python3 /home/ubuntu/Desktop/live2/CFFEW.py &
python3 /home/ubuntu/Desktop/live2/CFFI.py &
python3 /home/ubuntu/Desktop/live2/CFFN.py &
python3 /home/ubuntu/Desktop/live2/CFFSU.py &
python3 /home/ubuntu/Desktop/live2/CFFSW.py &
python3 /home/ubuntu/Desktop/live2/CFG.py &
python3 /home/ubuntu/Desktop/live2/CFIV.py &
python3 /home/ubuntu/Desktop/live2/CFIVW.py &
python3 /home/ubuntu/Desktop/live2/CFLT.py &
python3 /home/ubuntu/Desktop/live2/CFMS.py &
python3 /home/ubuntu/Desktop/live2/CFR.py &
python3 /home/ubuntu/Desktop/live2/CFRX.py &
python3 /home/ubuntu/Desktop/live2/CFSB.py &
python3 /home/ubuntu/Desktop/live2/CFVI.py &
python3 /home/ubuntu/Desktop/live2/CFVIU.py &
python3 /home/ubuntu/Desktop/live2/CFVIW.py &
python3 /home/ubuntu/Desktop/live2/CG.py &
python3 /home/ubuntu/Desktop/live2/CGA.py &
python3 /home/ubuntu/Desktop/live2/CGABL.py &
python3 /home/ubuntu/Desktop/live2/CGAU.py &
python3 /home/ubuntu/Desktop/live2/CGBD.py &
python3 /home/ubuntu/Desktop/live2/CGC.py &
python3 /home/ubuntu/Desktop/live2/CGEM.py &
python3 /home/ubuntu/Desktop/live2/CGEN.py &
python3 /home/ubuntu/Desktop/live2/CGNT.py &
python3 /home/ubuntu/Desktop/live2/CGNX.py &
python3 /home/ubuntu/Desktop/live2/CGO.py &
python3 /home/ubuntu/Desktop/live2/CGRN.py &
python3 /home/ubuntu/Desktop/live2/CGTX.py &
python3 /home/ubuntu/Desktop/live2/CHAA.py &
python3 /home/ubuntu/Desktop/live2/CHCI.py &
python3 /home/ubuntu/Desktop/live2/CHCO.py &
python3 /home/ubuntu/Desktop/live2/CHCT.py &
python3 /home/ubuntu/Desktop/live2/CHD.py &
python3 /home/ubuntu/Desktop/live2/CHDN.py &
python3 /home/ubuntu/Desktop/live2/CHE.py &
python3 /home/ubuntu/Desktop/live2/CHEAU.py &
python3 /home/ubuntu/Desktop/live2/CHEF.py &
python3 /home/ubuntu/Desktop/live2/CHEK.py &
python3 /home/ubuntu/Desktop/live2/CHEKZ.py &
python3 /home/ubuntu/Desktop/live2/CHGG.py &
python3 /home/ubuntu/Desktop/live2/CHH.py &
python3 /home/ubuntu/Desktop/live2/CHI.py &
python3 /home/ubuntu/Desktop/live2/CHK.py &
python3 /home/ubuntu/Desktop/live2/CHKEL.py &
python3 /home/ubuntu/Desktop/live2/CHKEW.py &
python3 /home/ubuntu/Desktop/live2/CHKEZ.py &
python3 /home/ubuntu/Desktop/live2/CHKP.py &
python3 /home/ubuntu/Desktop/live2/CHMG.py &
python3 /home/ubuntu/Desktop/live2/CHMI.py &
python3 /home/ubuntu/Desktop/live2/CHN.py &
python3 /home/ubuntu/Desktop/live2/CHNG.py &
python3 /home/ubuntu/Desktop/live2/CHNGU.py &
python3 /home/ubuntu/Desktop/live2/CHNR.py &
python3 /home/ubuntu/Desktop/live2/CHPT.py &
python3 /home/ubuntu/Desktop/live2/CHRA.py &
python3 /home/ubuntu/Desktop/live2/CHRB.py &
python3 /home/ubuntu/Desktop/live2/CHRS.py &
python3 /home/ubuntu/Desktop/live2/CHRW,.py &
python3 /home/ubuntu/Desktop/live2/CHS.py &
python3 /home/ubuntu/Desktop/live2/CHSCL.py &
python3 /home/ubuntu/Desktop/live2/CHSCM.py &
python3 /home/ubuntu/Desktop/live2/CHSCN.py &
python3 /home/ubuntu/Desktop/live2/CHSCO.py &
python3 /home/ubuntu/Desktop/live2/CHSCP.py &
python3 /home/ubuntu/Desktop/live2/CHT.py &
python3 /home/ubuntu/Desktop/live2/CHTR.py &
python3 /home/ubuntu/Desktop/live2/CHUY.py &
python3 /home/ubuntu/Desktop/live2/CHW.py &
python3 /home/ubuntu/Desktop/live2/CHWA.py &
python3 /home/ubuntu/Desktop/live2/CHWAW.py &
python3 /home/ubuntu/Desktop/live2/CHWY.py &
python3 /home/ubuntu/Desktop/live2/CHX.py &
python3 /home/ubuntu/Desktop/live2/CHY.py &
python3 /home/ubuntu/Desktop/live2/CI.py &
python3 /home/ubuntu/Desktop/live2/CIA.py &
python3 /home/ubuntu/Desktop/live2/CIB.py &
python3 /home/ubuntu/Desktop/live2/CIDM.py &
python3 /home/ubuntu/Desktop/live2/CIEN.py &
python3 /home/ubuntu/Desktop/live2/CIF.py &
python3 /home/ubuntu/Desktop/live2/CIFR.py &
python3 /home/ubuntu/Desktop/live2/CIFRW.py &
python3 /home/ubuntu/Desktop/live2/CIG.py &
python3 /home/ubuntu/Desktop/live2/CIGI.py &
python3 /home/ubuntu/Desktop/live2/CIH.py &
python3 /home/ubuntu/Desktop/live2/CII.py &
python3 /home/ubuntu/Desktop/live2/CIIG.py &
python3 /home/ubuntu/Desktop/live2/CIIGU.py &
python3 /home/ubuntu/Desktop/live2/CIK.py &
python3 /home/ubuntu/Desktop/live2/CIM.py &
python3 /home/ubuntu/Desktop/live2/CINC.py &
python3 /home/ubuntu/Desktop/live2/CINF.py &
python3 /home/ubuntu/Desktop/live2/CING.py &
python3 /home/ubuntu/Desktop/live2/CINGW.py &
python3 /home/ubuntu/Desktop/live2/CINT.py &
python3 /home/ubuntu/Desktop/live2/CIO.py &
python3 /home/ubuntu/Desktop/live2/CION.py &
python3 /home/ubuntu/Desktop/live2/CIR.py &
python3 /home/ubuntu/Desktop/live2/CISO.py &
python3 /home/ubuntu/Desktop/live2/CITE.py &
python3 /home/ubuntu/Desktop/live2/CITEU.py &
python3 /home/ubuntu/Desktop/live2/CIVB.py &
python3 /home/ubuntu/Desktop/live2/CIVI.py &
python3 /home/ubuntu/Desktop/live2/CIX.py &
python3 /home/ubuntu/Desktop/live2/CIXX.py &
python3 /home/ubuntu/Desktop/live2/CIZN.py &
python3 /home/ubuntu/Desktop/live2/CJJD.py &
python3 /home/ubuntu/Desktop/live2/CKPT.py &
python3 /home/ubuntu/Desktop/live2/CKX.py &
python3 /home/ubuntu/Desktop/live2/CL.py &
python3 /home/ubuntu/Desktop/live2/CLAA.py &
python3 /home/ubuntu/Desktop/live2/CLAQ.py &
python3 /home/ubuntu/Desktop/live2/CLAQR.py &
python3 /home/ubuntu/Desktop/live2/CLAQW.py &
python3 /home/ubuntu/Desktop/live2/CLB.py &
python3 /home/ubuntu/Desktop/live2/CLBK.py &
python3 /home/ubuntu/Desktop/live2/CLBR.py &
python3 /home/ubuntu/Desktop/live2/CLBS.py &
python3 /home/ubuntu/Desktop/live2/CLBT.py &
python3 /home/ubuntu/Desktop/live2/CLBTW.py &
python3 /home/ubuntu/Desktop/live2/CLDT.py &
python3 /home/ubuntu/Desktop/live2/CLDX.py &
python3 /home/ubuntu/Desktop/live2/CLEU.py &
python3 /home/ubuntu/Desktop/live2/CLF.py &
python3 /home/ubuntu/Desktop/live2/CLFD.py &
python3 /home/ubuntu/Desktop/live2/CLGN.py &
python3 /home/ubuntu/Desktop/live2/CLH.py &
python3 /home/ubuntu/Desktop/live2/CLIM.py &
python3 /home/ubuntu/Desktop/live2/CLINR.py &
python3 /home/ubuntu/Desktop/live2/CLINU.py &
python3 /home/ubuntu/Desktop/live2/CLINW.py &
python3 /home/ubuntu/Desktop/live2/CLIR.py &
python3 /home/ubuntu/Desktop/live2/CLLS.py &
python3 /home/ubuntu/Desktop/live2/CLM.py &
python3 /home/ubuntu/Desktop/live2/CLMT.py &
python3 /home/ubuntu/Desktop/live2/CLNE.py &
python3 /home/ubuntu/Desktop/live2/CLNN.py &
python3 /home/ubuntu/Desktop/live2/CLNNW.py &
python3 /home/ubuntu/Desktop/live2/CLOE.py &
python3 /home/ubuntu/Desktop/live2/CLOER.py &
python3 /home/ubuntu/Desktop/live2/CLOV.py &
python3 /home/ubuntu/Desktop/live2/CLPR.py &
python3 /home/ubuntu/Desktop/live2/CLPS.py &
python3 /home/ubuntu/Desktop/live2/CLPT.py &
python3 /home/ubuntu/Desktop/live2/CLR.py &
python3 /home/ubuntu/Desktop/live2/CLRB.py &
python3 /home/ubuntu/Desktop/live2/CLRCU.py &
python3 /home/ubuntu/Desktop/live2/CLRM.py &
python3 /home/ubuntu/Desktop/live2/CLRMU.py &
python3 /home/ubuntu/Desktop/live2/CLRMW.py &
python3 /home/ubuntu/Desktop/live2/CLRO.py &
python3 /home/ubuntu/Desktop/live2/CLS.py &
python3 /home/ubuntu/Desktop/live2/CLSD.py &
python3 /home/ubuntu/Desktop/live2/CLSK.py &
python3 /home/ubuntu/Desktop/live2/CLSN.py &
python3 /home/ubuntu/Desktop/live2/CLST.py &
python3 /home/ubuntu/Desktop/live2/CLVR.py &
python3 /home/ubuntu/Desktop/live2/CLVRW.py &
python3 /home/ubuntu/Desktop/live2/CLVS.py &
python3 /home/ubuntu/Desktop/live2/CLVT.py &
python3 /home/ubuntu/Desktop/live2/CLW.py &
python3 /home/ubuntu/Desktop/live2/CLWT.py &
python3 /home/ubuntu/Desktop/live2/CLX.py &
python3 /home/ubuntu/Desktop/live2/CLXT.py &
python3 /home/ubuntu/Desktop/live2/CM.py &
python3 /home/ubuntu/Desktop/live2/CMA.py &
python3 /home/ubuntu/Desktop/live2/CMAX.py &
python3 /home/ubuntu/Desktop/live2/CMAXW.py &
python3 /home/ubuntu/Desktop/live2/CMBM.py &
python3 /home/ubuntu/Desktop/live2/CMC.py &
python3 /home/ubuntu/Desktop/live2/CMCA.py &
python3 /home/ubuntu/Desktop/live2/CMCAU.py &
python3 /home/ubuntu/Desktop/live2/CMCL.py &
python3 /home/ubuntu/Desktop/live2/CMCM.py &
python3 /home/ubuntu/Desktop/live2/CMCO.py &
python3 /home/ubuntu/Desktop/live2/CMCSA.py &
python3 /home/ubuntu/Desktop/live2/CMCT.py
